# This is an example values.yaml file for the LangSmith Helm chart using the resources created via terraform.
# You can use this as a starting point for your own values.yaml file.

config:
  existingSecretName: "langsmith-secret-joaquin"  # Add your secret name here
  authType: "mixed"
  basicAuth:
    enabled: true
    initialOrgAdminEmail: "joaquin@langchain.dev"  # Add your email here
  blobStorage:
    enabled: true
    engine: "S3"
    bucketName: "langsmith-s3-joaquin"  # Add your bucket name here
    apiURL: "https://s3.us-west-2.amazonaws.com"  # Add your bucket API URL here

redis:
  external:
    enabled: true
    existingSecretName: "langsmith-redis-secret-joaquin"
    # existingSecretName: "<your-secret-name>" # Add your redis connection URL to the secret mentioned here.

postgres:
  external:
    enabled: true
    connectionUrl: "postgres://joaquin:joaquin123@langsmith-postgres-joaquin.cidvpg3q5pls.us-west-2.rds.amazonaws.com:5432/postgres"
    # existingSecretName: "<your-secret-name>" # Add your postgres connection URL to the secret mentioned here.

frontend:
  # This ensures you get a public endpoint for the application. It will be accessible over http with these settings.
  service:
    annotations:
      # service.beta.kubernetes.io/aws-load-balancer-type: "external"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" # If you want an internal lb, set this to "internal" and comment out the line above.

## Follow our docs here for more details: https://docs.smith.langchain.com/self_hosting/configuration/ingress
# ingress:
#   enabled: true
#   hostname: "" # Main domain for LangSmith
#   subdomain: "" # If you want to serve langsmith on a subdomain
#   ingressClassName: "" # If not set, the default ingress class will be used
#   annotations: {} # Add annotations here if needed
#   labels: {} # Add labels here if needed
#   tls: [] # Add TLS configuration here if needed
# frontend:
#   service:
#     type: ClusterIP

platformBackend:
  deployment:
    extraEnv:
      - name: AWS_REGION
        value: "us-west-2"
