variable "namespace" {
  type        = string
  description = "Kubernetes namespace for LangSmith"
  default     = "langsmith"
}

variable "postgres_connection_url" {
  type        = string
  description = "PostgreSQL connection URL (external: from RDS module; in-cluster: generated by root module)"
  sensitive   = true
}

# Extra keys needed by the in-cluster postgres chart to initialize the DB.
# Empty string when postgres_source = "external".
variable "postgres_in_cluster_user" {
  type      = string
  default   = ""
  sensitive = false
}
variable "postgres_in_cluster_db" {
  type    = string
  default = ""
}
variable "postgres_in_cluster_pass" {
  type      = string
  default   = ""
  sensitive = true
}

variable "redis_connection_url" {
  type        = string
  description = "Redis connection URL (external: from ElastiCache module; in-cluster: generated by root module)"
  sensitive   = true
}

variable "tls_certificate_source" {
  type        = string
  description = "TLS source: 'acm', 'letsencrypt', or 'none'"
  default     = "acm"
}

variable "letsencrypt_email" {
  type        = string
  description = "Email for Let's Encrypt certificate registration. Required when tls_certificate_source = 'letsencrypt'."
  default     = ""
}

variable "eso_irsa_role_arn" {
  type        = string
  description = "ARN of the IRSA role for the External Secrets Operator controller"
}

variable "enable_envoy_gateway" {
  type        = bool
  description = "Install Envoy Gateway for Kubernetes Gateway API routing"
  default     = false
}

variable "enable_istio_gateway" {
  type        = bool
  description = "Install Istio (istiod + istio-ingressgateway) for service mesh routing"
  default     = false
}

# ── cert-manager DNS-01 (Route 53 / Istio Gateway) ───────────────────────────
# These are populated from the cert-manager IRSA module when
# create_cert_manager_irsa = true. When empty, no DNS-01 resources are created.

variable "create_cert_manager_irsa" {
  type        = bool
  description = "True when the cert-manager IRSA role is being created. Used as a static bool gate for count= expressions to avoid plan-time dependency on computed module outputs."
  default     = false
}

variable "cert_manager_irsa_role_arn" {
  type        = string
  description = "IRSA role ARN for cert-manager Route 53 DNS-01. When non-empty, k8s-bootstrap installs cert-manager, creates a DNS-01 ClusterIssuer, requests a Certificate, and patches the Istio Gateway for HTTPS."
  default     = ""
}

variable "langsmith_domain" {
  type        = string
  description = "Domain for LangSmith (e.g. langsmith.example.com). Required for DNS-01 Certificate dnsNames and Istio Gateway host field."
  default     = ""
}

variable "region" {
  type        = string
  description = "AWS region — used in the Route 53 DNS-01 ClusterIssuer solver config."
  default     = "us-west-2"
}

variable "cert_manager_hosted_zone_id" {
  type        = string
  description = "Route 53 hosted zone ID for DNS-01 TXT record placement."
  default     = ""
}

variable "cluster_name" {
  type        = string
  description = "EKS cluster name — used to validate that kubectl is pointing at the correct cluster before applying any manifests."
  default     = ""
}

variable "gateway_target_group_arn" {
  type        = string
  description = "ARN of the Terraform-managed ALB target group for the gateway proxy. When non-empty and enable_envoy_gateway is true, a TargetGroupBinding is created in envoy-gateway-system so the ALB controller registers Envoy proxy pod IPs automatically."
  default     = ""
}

variable "enable_nginx_ingress" {
  type        = bool
  description = "Install NGINX ingress controller (ingress-nginx). When enabled, the ALB forwards to NGINX controller pods via a TargetGroupBinding, and LangSmith uses ingressClassName: nginx."
  default     = false
}
