# ══════════════════════════════════════════════════════════════════════════════
# Module: blob
# Purpose: Azure Blob Storage for LangSmith trace data + Workload Identity setup.
#
# LangSmith writes raw trace blobs (inputs/outputs, attachments) to blob storage
# rather than PostgreSQL to keep the database lean. Two TTL tiers:
#   ttl_s/ prefix  — short-lived traces, deleted after 14 days  (default)
#   ttl_l/ prefix  — long-lived  traces, deleted after 400 days (default)
#
# Authentication approach — Workload Identity (no static keys):
#   1. A User-Assigned Managed Identity is created.
#   2. It is granted "Storage Blob Data Contributor" on the storage account.
#   3. Federated Identity Credentials link Kubernetes service accounts to this
#      identity via OIDC — the AKS cluster acts as the OIDC token issuer.
#   4. LangSmith pods annotated with azure.workload.identity/client-id get
#      a short-lived token automatically — no key rotation needed.
#
# Three LangSmith service accounts need blob access:
#   • <release>-backend          — reads/writes trace blobs
#   • <release>-queue            — processes ingestion jobs that write blobs
#   • <release>-platform-backend — serves blob download URLs
# ══════════════════════════════════════════════════════════════════════════════

locals {
  # Kubernetes service accounts that need Workload Identity access to blob storage.
  # These names are generated by the LangSmith Helm chart: <release-name>-<service>.
  service_accounts_for_workload_identity = [
    # Pass 2 — core LangSmith
    "${var.langsmith_release_name}-backend",
    "${var.langsmith_release_name}-platform-backend",
    "${var.langsmith_release_name}-queue",
    "${var.langsmith_release_name}-ingest-queue",
    # Pass 3 — LangSmith Deployments
    "${var.langsmith_release_name}-host-backend",
    "${var.langsmith_release_name}-listener",
    # Pass 4 — Agent Builder
    "${var.langsmith_release_name}-agent-builder-tool-server",
    "${var.langsmith_release_name}-agent-builder-trigger-server",
  ]
}

# Azure Storage Account — the container for LangSmith trace blobs.
# Storage account names must be globally unique, lowercase alphanumeric, 3-24 chars.
# replace() strips hyphens from the input name to satisfy Azure naming rules.
# Standard LRS: locally-redundant storage — adequate for trace data.
# Upgrade to ZRS or GRS in Stage 3 for higher durability.
resource "azurerm_storage_account" "storage_account" {
  name                     = replace(var.storage_account_name, "-", "")
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS" # Stage 3: consider ZRS or RA-GRS
  tags                     = merge(var.tags, { module = "blob" })
}

# Blob container — private container that holds all LangSmith trace objects.
# Access is private: only the Managed Identity (via Workload Identity) can read/write.
# Objects are organized by prefix: ttl_s/ (short-lived) and ttl_l/ (long-lived).
resource "azurerm_storage_container" "container" {
  name                  = var.container_name
  storage_account_id    = azurerm_storage_account.storage_account.id
  container_access_type = "private"
}

# User-Assigned Managed Identity — the Azure AD identity for K8s pods.
# This is a named identity (not system-assigned) so it can be shared across
# multiple Kubernetes service accounts via federated credentials.
resource "azurerm_user_assigned_identity" "k8s_app" {
  name                = "k8s-app-identity"
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = merge(var.tags, { module = "blob" })
}

# Grant the Managed Identity permission to read and write blobs.
# "Storage Blob Data Contributor" allows: read, write, delete blobs.
# Scoped to the storage account (not the container) for flexibility.
resource "azurerm_role_assignment" "blob_data_contributor" {
  principal_id         = azurerm_user_assigned_identity.k8s_app.principal_id
  role_definition_name = "Storage Blob Data Contributor"
  scope                = azurerm_storage_account.storage_account.id
}

# Federated Identity Credentials — the bridge between K8s service accounts and Azure AD.
# Each credential says: "if a K8s service account <subject> in cluster <issuer>
# presents a token for audience <api://AzureADTokenExchange>, allow it to assume
# the Managed Identity <parent_id>."
#
# One credential per LangSmith service account (backend, queue, platform-backend).
# The AKS OIDC issuer URL is the trust anchor — must match the cluster's OIDC URL.
resource "azurerm_federated_identity_credential" "k8s_app" {
  for_each = toset(local.service_accounts_for_workload_identity)

  name      = "langsmith-federated-${each.value}"
  parent_id = azurerm_user_assigned_identity.k8s_app.id

  audience = [
    "api://AzureADTokenExchange" # standard audience for Azure Workload Identity
  ]

  # The OIDC issuer URL of the AKS cluster — this is the token signer that Azure
  # AD will trust when verifying the Kubernetes service account token.
  issuer = var.aks_oidc_issuer_url

  # "system:serviceaccount:<namespace>:<serviceaccount-name>" — the exact K8s
  # service account that will be allowed to assume this identity.
  subject = "system:serviceaccount:${var.langsmith_namespace}:${each.value}"
}

# Lifecycle management policy — automatic blob deletion based on age and prefix.
# This keeps storage costs bounded without manual cleanup.
#
# Rule "base":    delete ttl_s/* blobs after N days (default: 14)  — traces that
#                 the user hasn't explicitly kept long-term
# Rule "extended": delete ttl_l/* blobs after N days (default: 400) — traces
#                  explicitly marked for long retention (~13 months)
resource "azurerm_storage_management_policy" "lifecycle_policy" {
  count              = var.ttl_enabled ? 1 : 0
  storage_account_id = azurerm_storage_account.storage_account.id

  rule {
    name    = "base"
    enabled = true
    filters {
      prefix_match = ["${var.container_name}/ttl_s"]
      blob_types   = ["blockBlob"]
    }
    actions {
      base_blob {
        delete_after_days_since_creation_greater_than = var.ttl_short_days
      }
      snapshot {
        delete_after_days_since_creation_greater_than = var.ttl_short_days
      }
      version {
        delete_after_days_since_creation = var.ttl_short_days
      }
    }
  }

  rule {
    name    = "extended"
    enabled = true
    filters {
      prefix_match = ["${var.container_name}/ttl_l"]
      blob_types   = ["blockBlob"]
    }
    actions {
      base_blob {
        delete_after_days_since_creation_greater_than = var.ttl_long_days
      }
      snapshot {
        delete_after_days_since_creation_greater_than = var.ttl_long_days
      }
      version {
        delete_after_days_since_creation = var.ttl_long_days
      }
    }
  }
}
