# ┌─────────────────────────────────────────────────────────────────────────────┐
# │  Do not edit this file unless absolutely necessary.                       │
# │  Please edit terraform.tfvars for deployment configuration.               │
# │  See terraform.tfvars.example for all available options.                   │
# └─────────────────────────────────────────────────────────────────────────────┘

provider "aws" {
  region = var.region

  default_tags {
    tags = local.common_tags
  }
}

provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", module.eks.cluster_name, "--region", var.region]
  }
}

provider "helm" {
  kubernetes {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", module.eks.cluster_name, "--region", var.region]
    }
  }
}

# kubectl provider — used for the SmithDB Karpenter CRs (EC2NodeClass, NodePool).
# kubectl_manifest defers schema validation to apply time, so terraform plan
# succeeds on a fresh cluster before the Karpenter CRDs are installed (the
# controller is deployed by the eks module's blueprints add-on).
provider "kubectl" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  load_config_file       = false
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", module.eks.cluster_name, "--region", var.region]
  }
}

# ── Input validation ──────────────────────────────────────────────────────────
# Cross-variable checks that can't be expressed in variable validation blocks.
# These fire at plan time with a clear error message.

resource "terraform_data" "validate_inputs" {
  lifecycle {
    precondition {
      condition     = var.postgres_source != "external" || var.postgres_password != ""
      error_message = "postgres_password is required when postgres_source = 'external'. Run: source ./scripts/setup-env.sh, or set TF_VAR_postgres_password."
    }

    precondition {
      condition     = var.redis_source != "external" || (var.redis_auth_token != "" && length(var.redis_auth_token) >= 16)
      error_message = "redis_auth_token is required (min 16 chars) when redis_source = 'external'. Run: source ./scripts/setup-env.sh, or set TF_VAR_redis_auth_token."
    }

    precondition {
      condition     = var.tls_certificate_source != "acm" || var.acm_certificate_arn != "" || var.langsmith_domain != ""
      error_message = "When tls_certificate_source = 'acm', either acm_certificate_arn (existing cert) or langsmith_domain (auto-provision via Route 53) is required."
    }

    precondition {
      condition     = var.tls_certificate_source != "letsencrypt" || var.letsencrypt_email != ""
      error_message = "letsencrypt_email is required when tls_certificate_source = 'letsencrypt'."
    }

    precondition {
      condition     = var.create_vpc || (var.vpc_id != null && length(var.private_subnets) > 0 && var.vpc_cidr_block != null)
      error_message = "When create_vpc = false, vpc_id, private_subnets, and vpc_cidr_block must all be provided."
    }

    precondition {
      condition     = !var.create_firewall || var.create_vpc
      error_message = "create_firewall = true requires create_vpc = true. Bring-your-own-VPC deployments must configure firewall routing manually."
    }

    precondition {
      condition     = var.create_vpc || var.alb_scheme == "internal" || length(var.public_subnets) > 0
      error_message = "When create_vpc = false and alb_scheme = 'internet-facing', public_subnets must be provided."
    }

    precondition {
      condition     = !var.enable_agent_builder || var.enable_deployments
      error_message = "enable_agent_builder requires enable_deployments = true. Agent Builder depends on the Deployments feature."
    }

    precondition {
      condition     = !var.enable_polly || var.enable_deployments
      error_message = "enable_polly requires enable_deployments = true. Polly depends on the Deployments feature."
    }

    # Standalone agent features (chart v0.15+) run their own api-server + queue against
    # per-feature databases on the shared RDS/ElastiCache. They do NOT require
    # enable_deployments, but they DO require external Postgres and Redis to exist.
    precondition {
      condition     = !var.enable_fleet || (var.postgres_source == "external" && var.redis_source == "external")
      error_message = "enable_fleet requires postgres_source = \"external\" and redis_source = \"external\" (standalone Fleet uses a per-feature database on the shared RDS and a logical DB index on the shared ElastiCache)."
    }

    # Fleet's chat UI resolves OAuth provider/token connections through host-backend,
    # which only exists when Deployments is enabled. Without it the UI 500s on
    # /v1/platform/fleet/providers/.../connection ("host-backend ... no such host").
    precondition {
      condition     = !var.enable_fleet || var.enable_deployments
      error_message = "enable_fleet requires enable_deployments = true. The Fleet chat UI resolves OAuth provider/token connections via host-backend, which is only deployed when Deployments is enabled."
    }

    precondition {
      condition     = !var.enable_standalone_polly || (var.postgres_source == "external" && var.redis_source == "external")
      error_message = "enable_standalone_polly requires postgres_source = \"external\" and redis_source = \"external\" (standalone Polly uses a per-feature database on the shared RDS and a logical DB index on the shared ElastiCache)."
    }

    precondition {
      condition     = !var.enable_standalone_insights || (var.postgres_source == "external" && var.redis_source == "external")
      error_message = "enable_standalone_insights requires postgres_source = \"external\" and redis_source = \"external\" (standalone Insights uses a per-feature database on the shared RDS and a logical DB index on the shared ElastiCache)."
    }

    precondition {
      condition     = !(var.tls_certificate_source == "letsencrypt" && var.create_cert_manager_irsa)
      error_message = "tls_certificate_source = 'letsencrypt' (HTTP-01 via ALB) and create_cert_manager_irsa = true (DNS-01 via Route 53) are mutually exclusive. Both create ClusterIssuer/letsencrypt-prod. Use DNS-01 for Istio Gateway, HTTP-01 for ALB."
    }

    precondition {
      condition     = !var.create_cert_manager_irsa || var.cert_manager_hosted_zone_id != ""
      error_message = "cert_manager_hosted_zone_id is required when create_cert_manager_irsa = true. Find it: aws route53 list-hosted-zones --query 'HostedZones[*].[Name,Id]' --output table"
    }

    precondition {
      condition     = !var.create_cert_manager_irsa || var.letsencrypt_email != ""
      error_message = "letsencrypt_email is required when create_cert_manager_irsa = true (DNS-01 Let's Encrypt path)."
    }

    # SmithDB shares the LangSmith namespace/release (it cannot run standalone),
    # requires a dedicated metastore Postgres, and needs local-NVMe nodes.
    precondition {
      condition     = !var.enable_smithdb || var.smithdb_metastore_source == "create" || (var.smithdb_external_metastore_host != null && var.smithdb_external_metastore_username != null && var.smithdb_external_metastore_password != null)
      error_message = "enable_smithdb with smithdb_metastore_source = \"external\" requires smithdb_external_metastore_host, smithdb_external_metastore_username, and smithdb_external_metastore_password."
    }

    precondition {
      condition     = !var.enable_smithdb || var.smithdb_dockerhub_username == "" || var.smithdb_dockerhub_pat != ""
      error_message = "smithdb_dockerhub_pat is required when smithdb_dockerhub_username is set. Set TF_VAR_smithdb_dockerhub_pat."
    }
  }
}

module "vpc" {
  source = "./modules/vpc"

  count            = var.create_vpc ? 1 : 0
  vpc_name         = local.vpc_name
  cluster_name     = local.cluster_name
  firewall_enabled = var.create_firewall

  private_subnets = length(var.vpc_private_subnets) > 0 ? var.vpc_private_subnets : ["10.0.0.0/21", "10.0.8.0/21", "10.0.16.0/21"]
  public_subnets  = length(var.vpc_public_subnets) > 0 ? var.vpc_public_subnets : ["10.0.40.0/21", "10.0.48.0/21", "10.0.56.0/21"]

  # SmithDB Karpenter subnet discovery. Tag at creation so we avoid a for_each
  # over subnet IDs that are unknown until apply.
  extra_private_subnet_tags = var.enable_smithdb ? { "karpenter.sh/discovery" = local.cluster_name } : {}
}

module "firewall" {
  source = "./modules/firewall"
  count  = var.create_firewall ? 1 : 0

  name                    = local.firewall_name
  vpc_id                  = local.vpc_id
  nat_gateway_id          = module.vpc[0].nat_gateway_id
  nat_gateway_az          = module.vpc[0].nat_gateway_az
  firewall_subnet_cidr    = var.firewall_subnet_cidr
  private_route_table_ids = module.vpc[0].private_route_table_ids
  allowed_fqdns           = var.firewall_allowed_fqdns
  tags                    = local.common_tags

  depends_on = [module.vpc]
}

module "eks" {
  source = "./modules/eks"

  cluster_name                    = local.cluster_name
  cluster_version                 = var.eks_cluster_version
  vpc_id                          = local.vpc_id
  subnet_ids                      = concat(local.private_subnets, local.public_subnets)
  tags                            = local.common_tags
  create_gp3_storage_class        = var.create_gp3_storage_class
  eks_managed_node_group_defaults = var.eks_managed_node_group_defaults
  eks_managed_node_groups         = var.eks_managed_node_groups
  enable_karpenter                = var.enable_smithdb
  karpenter_chart_version         = var.smithdb_karpenter_chart_version
  public_cluster_enabled          = var.enable_public_eks_cluster
  public_access_cidrs             = var.eks_public_access_cidrs
  create_langsmith_irsa_role      = var.create_langsmith_irsa_role
  langsmith_namespace             = var.langsmith_namespace
  eks_addons                      = var.eks_addons
  cluster_enabled_log_types       = var.eks_cluster_enabled_log_types
  enable_istio_gateway            = var.enable_istio_gateway
}

# State migration: adding count changes the module address.
# These moved blocks tell Terraform the resources haven't changed — only their address has.
moved {
  from = module.postgres
  to   = module.postgres[0]
}

moved {
  from = module.redis
  to   = module.redis[0]
}

module "redis" {
  source = "./modules/redis"
  count  = var.redis_source == "external" ? 1 : 0

  name           = local.redis_name
  vpc_id         = local.vpc_id
  subnet_ids     = local.private_subnets
  instance_type  = var.redis_instance_type
  ingress_cidrs  = [local.vpc_cidr_block]
  vpc_cidr_block = local.vpc_cidr_block
  auth_token     = var.redis_auth_token
}

module "storage" {
  source = "./modules/storage"

  bucket_name             = local.bucket_name
  region                  = var.region
  vpc_id                  = local.vpc_id
  langsmith_irsa_role_arn = module.eks.langsmith_irsa_role_arn
  create_bucket_policy    = true
  s3_ttl_enabled          = var.s3_ttl_enabled
  s3_ttl_short_days       = var.s3_ttl_short_days
  s3_ttl_long_days        = var.s3_ttl_long_days
  kms_key_arn             = var.s3_kms_key_arn
  versioning_enabled      = var.s3_versioning_enabled
}

module "postgres" {
  source = "./modules/postgres"
  count  = var.postgres_source == "external" ? 1 : 0

  identifier     = local.postgres_name
  engine_version = var.postgres_engine_version
  vpc_id         = local.vpc_id
  subnet_ids     = local.private_subnets
  ingress_cidrs  = [local.vpc_cidr_block]
  vpc_cidr_block = local.vpc_cidr_block
  instance_type  = var.postgres_instance_type
  storage_gb     = var.postgres_storage_gb
  max_storage_gb = var.postgres_max_storage_gb
  username       = var.postgres_username
  password       = var.postgres_password

  iam_database_authentication_enabled = var.postgres_iam_database_authentication_enabled
  iam_database_user                   = var.postgres_iam_database_user
  iam_auth_role_name                  = module.eks.langsmith_irsa_role_name
  deletion_protection                 = var.postgres_deletion_protection
  backup_retention_period             = var.postgres_backup_retention_period

  depends_on = [module.eks]
}

resource "aws_iam_role_policy" "langsmith_s3" {
  count = var.create_langsmith_irsa_role ? 1 : 0

  name = "langsmith-s3-access"
  role = module.eks.langsmith_irsa_role_name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "S3Access"
        Effect = "Allow"
        Action = [
          "s3:GetObject",
          "s3:PutObject",
          "s3:DeleteObject",
          "s3:ListBucket",
        ]
        Resource = [
          module.storage.bucket_arn,
          "${module.storage.bucket_arn}/*",
        ]
      }
    ]
  })
}

# ── ESO IRSA role (External Secrets Operator) ─────────────────────────────
# Allows the ESO controller to read LangSmith secrets from SSM Parameter Store.
# IRSA: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
# ESO:  https://external-secrets.io/latest/provider/aws-parameter-store/

resource "aws_iam_role" "eso" {
  name = "${local.base_name}-eso"
  tags = local.common_tags

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = {
        Federated = module.eks.oidc_provider_arn
      }
      Action = "sts:AssumeRoleWithWebIdentity"
      Condition = {
        StringEquals = {
          "${module.eks.oidc_provider}:sub" = "system:serviceaccount:external-secrets:external-secrets"
          "${module.eks.oidc_provider}:aud" = "sts.amazonaws.com"
        }
      }
    }]
  })
}

resource "aws_iam_role_policy" "eso_ssm" {
  name = "eso-ssm-read"
  role = aws_iam_role.eso.name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "ssm:GetParameter",
        "ssm:GetParameters",
        "ssm:GetParametersByPath",
      ]
      Resource = "arn:aws:ssm:${var.region}:*:parameter/langsmith/${local.base_name}/*"
    }]
  })
}

# ── cert-manager IRSA ────────────────────────────────────────────────────────
# Provisions the IAM role + Route 53 policy for cert-manager DNS-01 challenges.
# Activated when create_cert_manager_irsa = true and a hosted_zone_id is set.
# After apply, run `make tls` to install cert-manager, create the ClusterIssuer,
# Certificate, and patch the Istio Gateway for HTTPS + HTTP redirect.

module "cert_manager" {
  source = "./modules/cert-manager"
  count  = var.create_cert_manager_irsa ? 1 : 0

  cluster_name      = local.cluster_name
  oidc_provider     = module.eks.oidc_provider
  oidc_provider_arn = module.eks.oidc_provider_arn
  hosted_zone_id    = var.cert_manager_hosted_zone_id
  tags              = local.common_tags

  depends_on = [module.eks]
}

# ── DNS / ACM ────────────────────────────────────────────────────────────────
# Activates whenever langsmith_domain is set (regardless of tls_certificate_source).
# This lets you deploy with tls_certificate_source = "none" first, delegate
# NS records at your leisure, then flip to "acm" in a later apply.
#
# When tls_certificate_source != "acm": creates the Route 53 zone, requests
# the ACM certificate, writes DNS validation records, and creates the alias
# record — but does NOT block waiting for certificate validation.
#
# When tls_certificate_source == "acm": additionally blocks until the ACM
# certificate is validated (NS delegation must be complete), then wires the
# validated cert into the ALB HTTPS listener.

locals {
  dns_enabled = var.langsmith_domain != "" && var.acm_certificate_arn == ""
}

module "dns" {
  source = "./modules/dns"
  count  = local.dns_enabled ? 1 : 0

  domain_name          = var.langsmith_domain
  create_zone          = true
  create_certificate   = true
  wait_for_validation  = var.tls_certificate_source == "acm"
  include_wildcard_san = var.dns_include_wildcard_san
}

# Alias record lives here (not in the dns module) to avoid a circular
# dependency: dns needs nothing from alb, and alb needs dns's cert ARN.
resource "aws_route53_record" "langsmith_alb_alias" {
  count   = local.dns_enabled ? 1 : 0
  zone_id = module.dns[0].zone_id
  name    = var.langsmith_domain
  type    = "A"

  alias {
    name                   = module.alb.alb_dns_name
    zone_id                = module.alb.alb_zone_id
    evaluate_target_health = true
  }
}

module "alb" {
  source = "./modules/alb"

  name                   = local.alb_name
  vpc_id                 = local.vpc_id
  vpc_cidr_block         = local.vpc_cidr_block
  subnets                = var.alb_scheme == "internal" ? local.private_subnets : local.public_subnets
  internal               = var.alb_scheme == "internal"
  allowed_cidr_blocks    = var.alb_allowed_cidr_blocks
  tls_certificate_source = var.tls_certificate_source
  acm_certificate_arn    = var.acm_certificate_arn != "" ? var.acm_certificate_arn : (local.dns_enabled && var.tls_certificate_source == "acm" ? module.dns[0].certificate_arn : "")
  access_logs_enabled    = var.alb_access_logs_enabled
  bucket_suffix          = random_id.bucket_suffix.hex
  enable_envoy_gateway   = var.enable_envoy_gateway
  enable_istio_gateway   = var.enable_istio_gateway
  enable_nginx_ingress   = var.enable_nginx_ingress
  tags                   = local.common_tags

  depends_on = [module.vpc]
}

# ── ALB → Gateway proxy: security group rule ─────────────────────────────────
# With target-type: ip, ALB sends traffic directly to pod IPs via VPC-CNI.
# The EKS cluster primary SG (attached to all nodes) blocks inbound from the ALB SG
# by default — only cluster-internal traffic is allowed. These rules open the specific
# gateway proxy port so ALB health checks and traffic can reach the pods.
#
# Envoy Gateway: port 10080 (Gateway listener port 80 + 10000 offset, Envoy runs non-root)
# Istio Gateway: port 80    (istio-ingressgateway listens on 80 directly via NET_BIND_SERVICE)
# NGINX Ingress:  port 80    (ingress-nginx-controller)

resource "aws_vpc_security_group_ingress_rule" "alb_to_envoy" {
  count = var.enable_envoy_gateway ? 1 : 0

  # Target the NODE security group (attached to EC2 instances and pod ENIs via VPC-CNI).
  # The cluster primary SG is on the control plane only — not on worker nodes.
  security_group_id            = module.eks.node_security_group_id
  referenced_security_group_id = module.alb.security_group_id
  from_port                    = 8080
  to_port                      = 8080
  ip_protocol                  = "tcp"
  description                  = "Allow ALB to reach Envoy Gateway proxy pods on HTTP (target-type: ip)"

  tags = local.common_tags
}

resource "aws_vpc_security_group_ingress_rule" "alb_to_istio" {
  count = var.enable_istio_gateway ? 1 : 0

  security_group_id            = module.eks.node_security_group_id
  referenced_security_group_id = module.alb.security_group_id
  from_port                    = 80
  to_port                      = 80
  ip_protocol                  = "tcp"
  description                  = "Allow ALB to reach Istio ingress gateway pods on HTTP (target-type: ip)"

  tags = local.common_tags
}

resource "aws_vpc_security_group_ingress_rule" "alb_to_nginx" {
  count = var.enable_nginx_ingress ? 1 : 0

  security_group_id            = module.eks.node_security_group_id
  referenced_security_group_id = module.alb.security_group_id
  from_port                    = 80
  to_port                      = 80
  ip_protocol                  = "tcp"
  description                  = "Allow ALB to reach NGINX ingress controller pods on HTTP (target-type: ip)"

  tags = local.common_tags
}

module "cloudtrail" {
  source = "./modules/cloudtrail"
  count  = var.create_cloudtrail ? 1 : 0

  trail_name            = "${local.base_name}-trail"
  bucket_name           = "${local.base_name}-cloudtrail-logs-${random_id.bucket_suffix.hex}"
  is_multi_region_trail = var.cloudtrail_multi_region
  log_retention_days    = var.cloudtrail_log_retention_days
  force_destroy         = true
  tags                  = local.common_tags
}

module "waf" {
  source = "./modules/waf"
  count  = var.create_waf ? 1 : 0

  name    = "${local.base_name}-waf"
  alb_arn = module.alb.alb_arn
  tags    = local.common_tags

  depends_on = [module.alb]
}

module "bastion" {
  source = "./modules/bastion"
  count  = var.create_bastion ? 1 : 0

  name                = local.bastion_name
  vpc_id              = local.vpc_id
  subnet_id           = var.bastion_enable_ssh ? local.public_subnets[0] : local.private_subnets[0]
  associate_public_ip = var.bastion_enable_ssh
  cluster_name        = local.cluster_name
  region              = var.region
  instance_type       = var.bastion_instance_type
  key_name            = var.bastion_key_name
  enable_ssh          = var.bastion_enable_ssh
  ssh_allowed_cidrs   = var.bastion_ssh_allowed_cidrs
  root_volume_size_gb = var.bastion_root_volume_size_gb
  tags                = local.common_tags

  depends_on = [module.vpc, module.eks]
}

# The ALB controller (installed by EKS blueprints) registers a mutating webhook
# that intercepts Service creation. Its pods need time to become ready after the
# EKS module completes. Without this delay, k8s-bootstrap Helm releases (ESO,
# KEDA) fail with "no endpoints available for service aws-load-balancer-webhook-service".
resource "time_sleep" "wait_for_alb_webhook" {
  depends_on      = [module.eks]
  create_duration = "30s"
}

# ── In-cluster credentials ────────────────────────────────────────────────────
# When postgres or redis runs in-cluster (deployed by the LangSmith Helm chart),
# Terraform still creates the k8s Secret so the chart can initialize the DB and
# backend pods can connect without manual patching after deploy.
# Passwords are generated here so they are stable across re-applies.

resource "random_password" "in_cluster_postgres" {
  count   = var.postgres_source == "in-cluster" ? 1 : 0
  length  = 32
  special = false
}


locals {
  postgres_connection_url = var.postgres_source == "external" ? module.postgres[0].connection_url : (
    "postgresql://langsmith:${random_password.in_cluster_postgres[0].result}@langsmith-postgres:5432/langsmith"
  )
  redis_connection_url = var.redis_source == "external" ? module.redis[0].connection_url : (
    "redis://langsmith-redis:6379"
  )
}

module "k8s_bootstrap" {
  source = "./modules/k8s-bootstrap"

  namespace = var.langsmith_namespace

  postgres_connection_url  = local.postgres_connection_url
  postgres_in_cluster_user = var.postgres_source == "in-cluster" ? "langsmith" : ""
  postgres_in_cluster_db   = var.postgres_source == "in-cluster" ? "langsmith" : ""
  postgres_in_cluster_pass = var.postgres_source == "in-cluster" ? random_password.in_cluster_postgres[0].result : ""

  redis_connection_url = local.redis_connection_url

  tls_certificate_source = var.tls_certificate_source
  letsencrypt_email      = var.letsencrypt_email

  eso_irsa_role_arn = aws_iam_role.eso.arn

  enable_envoy_gateway     = var.enable_envoy_gateway
  enable_istio_gateway     = var.enable_istio_gateway
  enable_nginx_ingress     = var.enable_nginx_ingress
  gateway_target_group_arn = module.alb.gateway_target_group_arn != null ? module.alb.gateway_target_group_arn : ""

  # cert-manager DNS-01 (Route 53 / Istio Gateway)
  # Pass create_cert_manager_irsa as a static bool so count= expressions in
  # k8s-bootstrap can be evaluated at plan time without depending on computed
  # module outputs (which are "known after apply" and cause plan-time errors).
  # The actual role ARN is still passed for runtime use (ClusterIssuer, SA annotation).
  create_cert_manager_irsa    = var.create_cert_manager_irsa
  cert_manager_irsa_role_arn  = length(module.cert_manager) > 0 ? module.cert_manager[0].cert_manager_irsa_role_arn : ""
  langsmith_domain            = var.langsmith_domain
  region                      = var.region
  cert_manager_hosted_zone_id = var.cert_manager_hosted_zone_id
  cluster_name                = local.cluster_name

  depends_on = [time_sleep.wait_for_alb_webhook, module.cert_manager]
}

#------------------------------------------------------------------------------
# Standalone Agent Features (chart v0.15+) — Fleet / Polly / Insights
#------------------------------------------------------------------------------
# Each standalone feature runs its own api-server + queue against a dedicated
# logical database on the shared RDS instance and a dedicated logical DB index
# on the shared ElastiCache. This mirrors the GCP module's per-feature backend
# (Cloud SQL database + Memorystore index) using AWS-native equivalents:
#   - RDS has no Terraform resource to create a logical database, so a one-shot
#     in-cluster psql Job runs CREATE DATABASE (it has a network path to the
#     private RDS instance; a local Terraform runner does not).
#   - ElastiCache (cluster-mode-disabled) supports logical DB indexes /1 /2 /3.
#     DB index 0 is reserved for the main LangSmith install.
# The K8s Secrets below feed the chart's fleet/polly/insights
# postgres.external.existingSecretName / redis.external.existingSecretName.

locals {
  # Admin base URL (no database) for the shared RDS instance. Guarded by the
  # external check so module.postgres[0] is only referenced when it exists.
  standalone_pg_base = var.postgres_source == "external" ? (
    "postgresql://${var.postgres_username}:${var.postgres_password}@${module.postgres[0].address}:${module.postgres[0].port}"
  ) : ""

  standalone_fleet_pg_url    = "${local.standalone_pg_base}/langsmith_fleet?sslmode=require"
  standalone_polly_pg_url    = "${local.standalone_pg_base}/langsmith_polly?sslmode=require"
  standalone_insights_pg_url = "${local.standalone_pg_base}/langsmith_insights?sslmode=require"

  # Shared ElastiCache base URL (rediss://:<token>@<endpoint>:6379). Append the
  # per-feature logical DB index. Guarded so module.redis[0] is only referenced
  # when it exists.
  standalone_redis_base = var.redis_source == "external" ? module.redis[0].connection_url : ""

  standalone_fleet_redis_url    = "${local.standalone_redis_base}/1"
  standalone_polly_redis_url    = "${local.standalone_redis_base}/2"
  standalone_insights_redis_url = "${local.standalone_redis_base}/3"
}

# ── Per-feature logical database creation (in-cluster psql Job) ───────────────
# Idempotent: skips CREATE DATABASE if the database already exists. Sources the
# admin connection URL from the langsmith-postgres Secret created by k8s-bootstrap
# so the master password is not embedded in the Job manifest.
resource "kubernetes_job_v1" "standalone_db" {
  for_each = {
    for k, v in {
      fleet    = var.enable_fleet
      polly    = var.enable_standalone_polly
      insights = var.enable_standalone_insights
    } : k => v if v && var.postgres_source == "external"
  }

  metadata {
    name      = "langsmith-standalone-${each.key}-db-init"
    namespace = var.langsmith_namespace
  }

  spec {
    backoff_limit = 6
    template {
      metadata {
        labels = {
          app     = "langsmith-standalone-db-init"
          feature = each.key
        }
      }
      spec {
        restart_policy = "Never"
        container {
          name  = "create-db"
          image = "postgres:16"
          command = [
            "/bin/sh",
            "-c",
            <<-EOT
              set -e
              DB="langsmith_${each.key}"
              if psql "$ADMIN_URL" -v ON_ERROR_STOP=1 -tAc "SELECT 1 FROM pg_database WHERE datname='$DB'" | grep -q 1; then
                echo "Database $DB already exists — nothing to do."
              else
                echo "Creating database $DB..."
                psql "$ADMIN_URL" -v ON_ERROR_STOP=1 -c "CREATE DATABASE \"$DB\""
                echo "Created database $DB."
              fi
            EOT
          ]
          env {
            name = "ADMIN_URL"
            value_from {
              secret_key_ref {
                name = "langsmith-postgres"
                key  = "connection_url"
              }
            }
          }
        }
      }
    }
  }

  wait_for_completion = true

  timeouts {
    create = "5m"
    update = "5m"
  }

  depends_on = [module.postgres, module.k8s_bootstrap]
}

# ── Per-feature connection-URL Secrets ────────────────────────────────────────
# Keys postgres_connection_url / redis_connection_url match what the chart's
# standalone fleet/polly/insights blocks read via existingSecretName.

resource "kubernetes_secret" "fleet_postgres" {
  count = var.enable_fleet && var.postgres_source == "external" ? 1 : 0
  metadata {
    name      = "langsmith-fleet-postgres"
    namespace = var.langsmith_namespace
  }
  data = {
    postgres_connection_url = local.standalone_fleet_pg_url
  }
  type       = "Opaque"
  depends_on = [kubernetes_job_v1.standalone_db, module.k8s_bootstrap]
}

resource "kubernetes_secret" "fleet_redis" {
  count = var.enable_fleet && var.redis_source == "external" ? 1 : 0
  metadata {
    name      = "langsmith-fleet-redis"
    namespace = var.langsmith_namespace
  }
  data = {
    redis_connection_url = local.standalone_fleet_redis_url
  }
  type       = "Opaque"
  depends_on = [module.k8s_bootstrap]
}

resource "kubernetes_secret" "standalone_polly_postgres" {
  count = var.enable_standalone_polly && var.postgres_source == "external" ? 1 : 0
  metadata {
    name      = "langsmith-polly-postgres"
    namespace = var.langsmith_namespace
  }
  data = {
    postgres_connection_url = local.standalone_polly_pg_url
  }
  type       = "Opaque"
  depends_on = [kubernetes_job_v1.standalone_db, module.k8s_bootstrap]
}

resource "kubernetes_secret" "standalone_polly_redis" {
  count = var.enable_standalone_polly && var.redis_source == "external" ? 1 : 0
  metadata {
    name      = "langsmith-polly-redis"
    namespace = var.langsmith_namespace
  }
  data = {
    redis_connection_url = local.standalone_polly_redis_url
  }
  type       = "Opaque"
  depends_on = [module.k8s_bootstrap]
}

resource "kubernetes_secret" "standalone_insights_postgres" {
  count = var.enable_standalone_insights && var.postgres_source == "external" ? 1 : 0
  metadata {
    name      = "langsmith-insights-postgres"
    namespace = var.langsmith_namespace
  }
  data = {
    postgres_connection_url = local.standalone_insights_pg_url
  }
  type       = "Opaque"
  depends_on = [kubernetes_job_v1.standalone_db, module.k8s_bootstrap]
}

resource "kubernetes_secret" "standalone_insights_redis" {
  count = var.enable_standalone_insights && var.redis_source == "external" ? 1 : 0
  metadata {
    name      = "langsmith-insights-redis"
    namespace = var.langsmith_namespace
  }
  data = {
    redis_connection_url = local.standalone_insights_redis_url
  }
  type       = "Opaque"
  depends_on = [module.k8s_bootstrap]
}

#------------------------------------------------------------------------------
# SmithDB (chart 0.16+) — dedicated metastore, object store, IRSA, and the
# Kubernetes secrets the chart consumes. Node groups are wired into module.eks
# above. The Helm release (smithdb.enabled) is deployed in Pass 2.
#------------------------------------------------------------------------------

locals {
  smithdb_name        = "${local.base_name}-smithdb"
  smithdb_bucket_name = var.smithdb_bucket_name != "" ? var.smithdb_bucket_name : "${local.base_name}-smithdb-${random_id.bucket_suffix.hex}"

  # Docker Hub image-pull secret for private SmithDB images (early access).
  smithdb_dockerhub_config_json = var.enable_smithdb && var.smithdb_dockerhub_username != "" ? jsonencode({
    auths = {
      "https://index.docker.io/v1/" = {
        username = var.smithdb_dockerhub_username
        password = var.smithdb_dockerhub_pat
        auth     = base64encode("${var.smithdb_dockerhub_username}:${var.smithdb_dockerhub_pat}")
      }
    }
  }) : null
}

module "smithdb" {
  source = "./modules/smithdb"
  count  = var.enable_smithdb ? 1 : 0

  name         = local.smithdb_name
  region       = var.region
  tags         = local.common_tags
  namespace    = var.langsmith_namespace
  release_name = var.langsmith_release_name

  vpc_id                     = local.vpc_id
  private_subnet_ids         = local.private_subnets
  eks_node_security_group_id = module.eks.node_security_group_id
  eks_oidc_provider_arn      = module.eks.oidc_provider_arn
  eks_oidc_provider_url      = module.eks.oidc_provider

  # Metastore
  metastore_source                  = var.smithdb_metastore_source
  metastore_instance_class          = var.smithdb_metastore_instance_class
  metastore_engine_version          = var.smithdb_metastore_engine_version
  metastore_allocated_storage       = var.smithdb_metastore_allocated_storage
  metastore_multi_az                = var.smithdb_metastore_multi_az
  metastore_deletion_protection     = var.smithdb_metastore_deletion_protection
  metastore_backup_retention_period = var.smithdb_metastore_backup_retention_period
  metastore_skip_final_snapshot     = var.smithdb_metastore_skip_final_snapshot
  metastore_master_username         = var.smithdb_metastore_master_username

  external_metastore_host     = var.smithdb_external_metastore_host
  external_metastore_port     = var.smithdb_external_metastore_port
  external_metastore_database = var.smithdb_external_metastore_database
  external_metastore_username = var.smithdb_external_metastore_username
  external_metastore_password = var.smithdb_external_metastore_password

  # Object store
  bucket_name           = local.smithdb_bucket_name
  s3_kms_key_arn        = var.s3_kms_key_arn
  s3_versioning_enabled = var.smithdb_s3_versioning_enabled
  s3_force_destroy      = var.smithdb_s3_force_destroy

  depends_on = [module.eks]
}

# Metastore connection secret consumed by smithdb.config.existingSecretName.
# S3 credentials are intentionally absent — SmithDB pods use IRSA instead.
resource "kubernetes_secret" "smithdb_local" {
  count = var.enable_smithdb ? 1 : 0

  metadata {
    name      = "smithdb-local"
    namespace = var.langsmith_namespace
  }
  data = {
    smithdb_metastore_db_host     = module.smithdb[0].metastore_host
    smithdb_metastore_db_name     = module.smithdb[0].metastore_database
    smithdb_metastore_db_username = module.smithdb[0].metastore_username
    smithdb_metastore_db_password = module.smithdb[0].metastore_password
  }
  type       = "Opaque"
  depends_on = [module.k8s_bootstrap]
}

# Optional image-pull secret for private (early-access) SmithDB images.
resource "kubernetes_secret" "smithdb_dockerhub" {
  count = local.smithdb_dockerhub_config_json == null ? 0 : 1

  metadata {
    name      = "dockerhub-private"
    namespace = var.langsmith_namespace
  }
  type = "kubernetes.io/dockerconfigjson"
  data = {
    ".dockerconfigjson" = local.smithdb_dockerhub_config_json
  }
  depends_on = [module.k8s_bootstrap]
}

#------------------------------------------------------------------------------
# SmithDB Karpenter provisioning
#
# The Karpenter controller is installed by module.eks (blueprints add-on). Here
# we tag the discovery targets and create the SmithDB NodePools/EC2NodeClasses:
#   - instance-store: local-NVMe nodes, RAID0'd by Karpenter (instanceStorePolicy)
#     for the SmithDB emptyDir caches. Hosts query / ingestion / compaction-worker.
#   - compute: no local NVMe. Hosts compaction / cluster-manager and the transient
#     metastore-migration job.
# Labels/taints (smithdb-local/instance-store, smithdb-local/compute) match the
# nodeSelectors/tolerations in langsmith-values-smithdb.yaml.
#------------------------------------------------------------------------------

locals {
  # Subnets are discovered by the karpenter.sh/discovery tag (applied to the
  # private subnets at creation via the vpc module's extra_private_subnet_tags).
  smithdb_karpenter_discovery = { "karpenter.sh/discovery" = local.cluster_name }

  # Security groups are discovered by the EKS-managed cluster tag
  # (kubernetes.io/cluster/<cluster> = owned), which is stable and always present
  # on the cluster security group. We deliberately do NOT put karpenter.sh/discovery
  # on the node SG ourselves: the EKS module reconciles node-SG tags and can drop
  # an out-of-band tag, leaving the EC2NodeClass with SecurityGroupsReady=False.
  smithdb_karpenter_sg_selector = { "kubernetes.io/cluster/${local.cluster_name}" = "owned" }
}

# EC2NodeClass subnet discovery for a bring-your-own VPC: tag the existing private
# subnets here (a for_each is safe because their IDs are known statically). For a
# Terraform-created VPC the tag is applied at creation via the vpc module's
# extra_private_subnet_tags (above).
resource "aws_ec2_tag" "smithdb_karpenter_subnet" {
  for_each = var.enable_smithdb && !var.create_vpc ? toset(var.private_subnets) : toset([])

  resource_id = each.value
  key         = "karpenter.sh/discovery"
  value       = local.cluster_name
}

resource "kubectl_manifest" "smithdb_ec2nc_instance_store" {
  count = var.enable_smithdb ? 1 : 0

  yaml_body = yamlencode({
    apiVersion = "karpenter.k8s.aws/v1"
    kind       = "EC2NodeClass"
    metadata   = { name = "smithdb-instance-store" }
    spec = {
      amiSelectorTerms           = [{ alias = var.smithdb_karpenter_ami_alias }]
      role                       = module.eks.karpenter_node_iam_role_name
      subnetSelectorTerms        = [{ tags = local.smithdb_karpenter_discovery }]
      securityGroupSelectorTerms = [{ tags = local.smithdb_karpenter_sg_selector }]
      associatePublicIPAddress   = false
      # Karpenter RAID0s the local NVMe and points kubelet at it — no userdata.
      instanceStorePolicy = "RAID0"
      metadataOptions = {
        httpEndpoint            = "enabled"
        httpProtocolIPv6        = "disabled"
        httpPutResponseHopLimit = 1
        httpTokens              = "required"
      }
      blockDeviceMappings = [{
        deviceName = "/dev/xvda"
        ebs = {
          volumeSize = "${var.smithdb_node_root_volume_size_gb}Gi"
          volumeType = "gp3"
          encrypted  = true
        }
      }]
    }
  })

  depends_on = [module.eks]
}

resource "kubectl_manifest" "smithdb_ec2nc_compute" {
  count = var.enable_smithdb ? 1 : 0

  yaml_body = yamlencode({
    apiVersion = "karpenter.k8s.aws/v1"
    kind       = "EC2NodeClass"
    metadata   = { name = "smithdb-compute" }
    spec = {
      amiSelectorTerms           = [{ alias = var.smithdb_karpenter_ami_alias }]
      role                       = module.eks.karpenter_node_iam_role_name
      subnetSelectorTerms        = [{ tags = local.smithdb_karpenter_discovery }]
      securityGroupSelectorTerms = [{ tags = local.smithdb_karpenter_sg_selector }]
      associatePublicIPAddress   = false
      metadataOptions = {
        httpEndpoint            = "enabled"
        httpProtocolIPv6        = "disabled"
        httpPutResponseHopLimit = 1
        httpTokens              = "required"
      }
      blockDeviceMappings = [{
        deviceName = "/dev/xvda"
        ebs = {
          volumeSize = "${var.smithdb_node_root_volume_size_gb}Gi"
          volumeType = "gp3"
          encrypted  = true
        }
      }]
    }
  })

  depends_on = [module.eks]
}

resource "kubectl_manifest" "smithdb_nodepool_instance_store" {
  count = var.enable_smithdb ? 1 : 0

  yaml_body = yamlencode({
    apiVersion = "karpenter.sh/v1"
    kind       = "NodePool"
    metadata   = { name = "smithdb-instance-store" }
    spec = {
      template = {
        metadata = { labels = { "smithdb-local/instance-store" = "true" } }
        spec = {
          taints = [{ key = "smithdb-local/instance-store", value = "true", effect = "NoSchedule" }]
          requirements = [
            { key = "kubernetes.io/os", operator = "In", values = ["linux"] },
            { key = "kubernetes.io/arch", operator = "In", values = [var.smithdb_node_arch] },
            { key = "karpenter.sh/capacity-type", operator = "In", values = var.smithdb_capacity_type },
            { key = "karpenter.k8s.aws/instance-generation", operator = "Gt", values = ["2"] },
            { key = "karpenter.k8s.aws/instance-local-nvme", operator = "Gt", values = [tostring(var.smithdb_instance_store_min_local_nvme_gib - 1)] },
            { key = "karpenter.k8s.aws/instance-size", operator = "In", values = var.smithdb_instance_store_sizes },
          ]
          nodeClassRef = {
            group = "karpenter.k8s.aws"
            kind  = "EC2NodeClass"
            name  = "smithdb-instance-store"
          }
          expireAfter = "720h"
        }
      }
      limits = {
        cpu    = tostring(var.smithdb_instance_store_limits.cpu)
        memory = var.smithdb_instance_store_limits.memory
      }
      # Avoid churn for nodes holding large local caches.
      disruption = {
        consolidationPolicy = "WhenEmpty"
        consolidateAfter    = "2m"
        budgets             = [{ nodes = "10%" }]
      }
    }
  })

  depends_on = [kubectl_manifest.smithdb_ec2nc_instance_store]
}

resource "kubectl_manifest" "smithdb_nodepool_compute" {
  count = var.enable_smithdb ? 1 : 0

  yaml_body = yamlencode({
    apiVersion = "karpenter.sh/v1"
    kind       = "NodePool"
    metadata   = { name = "smithdb-compute" }
    spec = {
      template = {
        metadata = { labels = { "smithdb-local/compute" = "true" } }
        spec = {
          taints = [{ key = "smithdb-local/compute", value = "true", effect = "NoSchedule" }]
          requirements = [
            { key = "kubernetes.io/os", operator = "In", values = ["linux"] },
            { key = "kubernetes.io/arch", operator = "In", values = [var.smithdb_node_arch] },
            { key = "karpenter.sh/capacity-type", operator = "In", values = var.smithdb_capacity_type },
            { key = "karpenter.k8s.aws/instance-generation", operator = "Gt", values = ["2"] },
            { key = "karpenter.k8s.aws/instance-size", operator = "In", values = var.smithdb_compute_sizes },
          ]
          nodeClassRef = {
            group = "karpenter.k8s.aws"
            kind  = "EC2NodeClass"
            name  = "smithdb-compute"
          }
          expireAfter = "720h"
        }
      }
      limits = {
        cpu    = tostring(var.smithdb_compute_limits.cpu)
        memory = var.smithdb_compute_limits.memory
      }
      disruption = {
        consolidationPolicy = "WhenEmptyOrUnderutilized"
        consolidateAfter    = "2m"
        budgets             = [{ nodes = "10%" }]
      }
    }
  })

  depends_on = [kubectl_manifest.smithdb_ec2nc_compute]
}
