#!/usr/bin/env bash
set -euo pipefail
# clean.sh — Remove all local generated/sensitive files after teardown.
#
# Usage (from azure/):
#   make clean
#
# Removes:
#   infra/terraform.tfvars          — live deployment config
#   infra/secrets.auto.tfvars       — generated secrets (Key Vault seed values)
#   infra/.api_key_salt etc.        — temp secret files written by setup-env.sh
#   infra/terraform.tfstate         — local state (only present when not using remote backend)
#   infra/terraform.tfstate.backup  — state backup files
#   helm/values/values-overrides.yaml          — generated by init-values.sh
#   helm/values/values.yaml                    — copied from chart defaults
#   helm/values/langsmith-values-*.yaml        — sizing + addon overlays
#
# Does NOT remove:
#   infra/terraform.tfvars.example  — template, keep it
#   helm/values/examples/           — reference files, keep them
#   .terraform/                     — provider cache, not sensitive

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
AZURE_DIR="$(cd "$INFRA_DIR/.." && pwd)"
HELM_VALUES_DIR="$AZURE_DIR/helm/values"

source "$SCRIPT_DIR/_common.sh"

echo ""
echo "══════════════════════════════════════════════════════"
echo "  LangSmith Azure — Clean local files"
echo "══════════════════════════════════════════════════════"
echo ""
warn "This removes all local secrets and generated values files."
warn "Run AFTER: make uninstall && make destroy"
echo ""
printf "  Continue? [y/N] "
read -r _confirm
[[ "$_confirm" =~ ^[Yy]$ ]] || { echo "  Aborted."; exit 0; }
echo ""

_removed=0

_rm() {
  if [[ -f "$1" ]]; then
    rm -f "$1"
    pass "Removed: ${1#$AZURE_DIR/}"
    _removed=$((_removed + 1))
  fi
}

# ── Terraform secrets and live config ─────────────────────────────────────────
header "Terraform"
_rm "$INFRA_DIR/terraform.tfvars"
_rm "$INFRA_DIR/secrets.auto.tfvars"

# Temp secret files written by setup-env.sh before Key Vault exists
for f in .api_key_salt .jwt_secret .deployments_key .agent_builder_key .insights_key .polly_key; do
  _rm "$INFRA_DIR/$f"
done

# Terraform state files (only present when not using a remote backend)
_rm "$INFRA_DIR/terraform.tfstate"
_rm "$INFRA_DIR/terraform.tfstate.backup"
for f in "$INFRA_DIR"/terraform.tfstate.*.backup; do
  [[ -f "$f" ]] && _rm "$f"
done

# ── Helm generated values ─────────────────────────────────────────────────────
header "Helm values"
_rm "$HELM_VALUES_DIR/values-overrides.yaml"
_rm "$HELM_VALUES_DIR/values.yaml"

for f in "$HELM_VALUES_DIR"/langsmith-values-*.yaml; do
  [[ -f "$f" ]] && _rm "$f"
done

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
if [[ $_removed -eq 0 ]]; then
  skip "Nothing to remove — already clean"
else
  pass "$_removed file(s) removed"
fi
echo ""
info "To redeploy from scratch:"
info "  make setup-env → make init → make apply → make deploy-all"
echo ""
