#!/usr/bin/env bash

# MIT License - Copyright (c) 2026 LangChain, Inc.
# NOTICE: Actively being tested and subject to change. Not officially supported by LangChain.
# See LICENSE at the root of this repository for full license text.

set -euo pipefail
# setup-env.sh — Bootstrap Terraform inputs for LangSmith (Pass 1)
#
# Usage:
#   ./setup-env.sh
#
# Writes the values Terraform itself needs to secrets.auto.tfvars (gitignored).
# Terraform picks this file up automatically — no shell session coupling needed.
#
# Only two secrets reach Terraform, because Terraform needs them to build
# something and would hold them in state either way:
#   postgres_admin_password — Terraform creates the Postgres flexible server
#   langsmith_license_key   — the k8s_bootstrap module creates the
#                             langsmith-license K8s secret from it
#
# The LangSmith app secrets (admin password, API key salt, JWT secret, Fernet
# encryption keys) are NOT handled here. Terraform would persist their plaintext
# in state, so scripts/seed-keyvault-secrets.sh writes them directly to Key Vault
# after apply. Run `make seed-secrets` between `make apply` and `make k8s-secrets`.

SECRETS_FILE="secrets.auto.tfvars"

# ── Prompt helper (skips if env var already set) ──────────────────────────────
# If stdin is not a tty and the env var is not set, exit with a clear error
# rather than silently storing empty/garbage values in secrets.auto.tfvars.
_prompt() {
  local env_var="$1"
  local prompt_text="$2"
  local val="${!env_var:-}"
  if [[ -z "$val" ]]; then
    if [[ ! -t 0 ]]; then
      echo "ERROR: setup-env.sh requires interactive input (stdin is not a tty)." >&2
      echo "       Set env vars to skip prompts:" >&2
      echo "         export LANGSMITH_PG_PASSWORD=..." >&2
      echo "         export LANGSMITH_LICENSE_KEY=..." >&2
      echo "         export LANGSMITH_ADMIN_EMAIL=..." >&2
      echo "       Then re-run: make setup-env" >&2
      exit 1
    fi
    printf "%s: " "$prompt_text"
    read -rs val
    echo
  fi
  echo "$val"
}

# ── Collect secrets ───────────────────────────────────────────────────────────
echo ""
echo "LangSmith — Terraform input bootstrap"
echo ""

pg_password=$(_prompt "LANGSMITH_PG_PASSWORD"  "PostgreSQL admin password  ")
license_key=$(_prompt "LANGSMITH_LICENSE_KEY"  "LangSmith license key      ")
admin_email=$(_prompt "LANGSMITH_ADMIN_EMAIL"  "Initial org admin email    ")

# ── Write secrets.auto.tfvars ─────────────────────────────────────────────────
cat > "$SECRETS_FILE" << EOF
# Auto-generated by setup-env.sh — DO NOT COMMIT
# Re-run ./setup-env.sh to regenerate.

postgres_admin_password = "$pg_password"
langsmith_license_key   = "$license_key"
langsmith_admin_email   = "$admin_email"
EOF

chmod 600 "$SECRETS_FILE"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "  Wrote $SECRETS_FILE (chmod 600)"
echo ""
echo "Next (from terraform/azure/):"
echo "  make preflight     # verify az login, providers, RBAC"
echo "  make init          # terraform init"
echo "  make apply         # deploy AKS + Postgres + Redis + Blob + Key Vault"
echo "  make seed-secrets  # write LangSmith app secrets into Key Vault"
echo "  make kubeconfig    # fetch AKS credentials"
echo "  make k8s-secrets   # create langsmith-config-secret from Key Vault"
echo "  make init-values   # generate Helm values from Terraform outputs"
echo "  make deploy        # helm upgrade --install langsmith"
