#!/usr/bin/env bash
set -euo pipefail
# setup-env.sh — Bootstrap LangSmith secrets for Terraform (Pass 1)
#
# Usage:
#   ./setup-env.sh
#
# Writes all sensitive variables to secrets.auto.tfvars (gitignored).
# Terraform picks this file up automatically — no shell session coupling needed.
#
# On first run:  prompts for passwords, generates stable secrets → local files + secrets.auto.tfvars.
#                Terraform apply then creates Key Vault and stores all secrets in it.
# On subsequent runs:  reads silently from Key Vault → secrets.auto.tfvars. No prompts.
#
# setup-env.sh is READ-ONLY against Key Vault — it never writes to KV directly.
# Terraform is the sole writer. This prevents state conflicts on terraform apply.

SECRETS_FILE="secrets.auto.tfvars"

# ── Read identifier from terraform.tfvars ─────────────────────────────────────
_identifier=""
if [[ -f "terraform.tfvars" ]]; then
  _identifier=$(grep -E '^\s*identifier\s*=' terraform.tfvars \
    | sed 's/.*=[[:space:]]*"\([^"]*\)".*/\1/' \
    | tr -d '[:space:]') || _identifier=""
fi
_kv_name="langsmith-kv${_identifier}"

# ── Prompt helper (skips if env var already set) ──────────────────────────────
_prompt() {
  local env_var="$1"
  local prompt_text="$2"
  local val="${!env_var:-}"
  if [[ -z "$val" ]]; then
    printf "%s: " "$prompt_text"
    read -rs val
    echo
  fi
  echo "$val"
}

# ── Stable secret: read from Key Vault or local fallback, generate if missing ──
# Priority: Key Vault (written by Terraform) → local fallback file → generate fresh
# Never writes to Key Vault directly — Terraform owns all KV writes.
_kv_secret() {
  local kv_secret_name="$1"
  local fallback_file="$2"
  local generator="$3"
  local val=""

  # 1. Read from Key Vault (available after terraform apply)
  if az keyvault show --name "$_kv_name" --output none 2>/dev/null; then
    val=$(az keyvault secret show \
      --vault-name "$_kv_name" \
      --name "$kv_secret_name" \
      --query value -o tsv 2>/dev/null) || val=""
  fi

  # 2. Fall back to local file (before first apply, or on a machine without KV access)
  if [[ -z "$val" && -f "$fallback_file" ]]; then
    val=$(cat "$fallback_file")
  fi

  # 3. Generate fresh — write to local file only; Terraform stores in Key Vault on apply
  if [[ -z "$val" ]]; then
    val=$(eval "$generator")
    echo "$val" > "$fallback_file"
    echo "  Generated $kv_secret_name → $fallback_file (Terraform stores in Key Vault on apply)" >&2
  fi

  echo "$val"
}

_fernet_generator='python3 -c "
try:
    from cryptography.fernet import Fernet
    print(Fernet.generate_key().decode())
except ImportError:
    import base64, os
    print(base64.urlsafe_b64encode(os.urandom(32)).decode())
"'

# ── Collect secrets ───────────────────────────────────────────────────────────
echo ""
echo "LangSmith — secret bootstrap"
echo "  identifier : ${_identifier:-(empty)}"
echo "  key_vault  : $_kv_name"
echo ""

pg_password=$(_prompt "LANGSMITH_PG_PASSWORD"     "PostgreSQL admin password  ")
license_key=$(_prompt "LANGSMITH_LICENSE_KEY"      "LangSmith license key      ")
admin_password=$(_prompt "LANGSMITH_ADMIN_PASSWORD" "LangSmith admin password   ")
admin_email=$(_prompt "LANGSMITH_ADMIN_EMAIL"      "Initial org admin email    ")

echo ""
echo "  Resolving stable secrets..."
api_key_salt=$(_kv_secret "langsmith-api-key-salt"               ".api_key_salt"    "openssl rand -base64 32")
jwt_secret=$(_kv_secret   "langsmith-jwt-secret"                 ".jwt_secret"      "openssl rand -base64 32")
deployments_key=$(_kv_secret "langsmith-deployments-encryption-key" ".deployments_key" "$_fernet_generator")
agent_builder_key=$(_kv_secret "langsmith-agent-builder-encryption-key" ".agent_builder_key" "$_fernet_generator")
insights_key=$(_kv_secret "langsmith-insights-encryption-key"    ".insights_key"    "$_fernet_generator")
polly_key=$(_kv_secret    "langsmith-polly-encryption-key"        ".polly_key"       "$_fernet_generator")

# ── Write secrets.auto.tfvars ─────────────────────────────────────────────────
cat > "$SECRETS_FILE" << EOF
# Auto-generated by setup-env.sh — DO NOT COMMIT
# Re-run ./setup-env.sh to refresh secrets from Key Vault.

postgres_admin_password                = "$pg_password"
langsmith_license_key                  = "$license_key"
langsmith_admin_password               = "$admin_password"
langsmith_admin_email                  = "$admin_email"
langsmith_api_key_salt                 = "$api_key_salt"
langsmith_jwt_secret                   = "$jwt_secret"
langsmith_deployments_encryption_key   = "$deployments_key"
langsmith_agent_builder_encryption_key = "$agent_builder_key"
langsmith_insights_encryption_key      = "$insights_key"
langsmith_polly_encryption_key         = "$polly_key"
EOF

chmod 600 "$SECRETS_FILE"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "  Wrote $SECRETS_FILE (chmod 600)"
echo ""
echo "Next:"
echo "  terraform init    # first run only"
echo "  terraform plan"
echo "  terraform apply"
echo ""
echo "Next (from terraform/azure/):"
echo "  make preflight     # verify az login, providers, RBAC"
echo "  make init          # terraform init"
echo "  make apply         # deploy AKS + Postgres + Redis + Blob + Key Vault"
echo "  make kubeconfig    # fetch AKS credentials"
echo "  make k8s-secrets   # create langsmith-config-secret from Key Vault"
echo "  make init-values   # generate Helm values from Terraform outputs"
echo "  make deploy        # helm upgrade --install langsmith"
