#!/usr/bin/env bash

# MIT License - Copyright (c) 2026 LangChain, Inc.
# NOTICE: Actively being tested and subject to change. Not officially supported by LangChain.
# See LICENSE at the root of this repository for full license text.

set -euo pipefail
# setup-env.sh — Bootstrap Terraform inputs for LangSmith (Pass 1)
#
# Usage:
#   ./setup-env.sh
#
# Writes the values Terraform itself needs to secrets.auto.tfvars (gitignored).
# Terraform picks this file up automatically — no shell session coupling needed.
#
# Only two secrets reach Terraform, because Terraform needs them to build
# something and would hold them in state either way:
#   postgres_admin_password — Terraform creates the Postgres flexible server
#   langsmith_license_key   — the k8s_bootstrap module creates the
#                             langsmith-license K8s secret from it
#
# The LangSmith app secrets (admin password, API key salt, JWT secret, Fernet
# encryption keys) are NOT handled here. Terraform would persist their plaintext
# in state, so scripts/seed-keyvault-secrets.sh writes them directly to Key Vault
# after apply. Run `make seed-secrets` between `make apply` and `make k8s-secrets`.

SECRETS_FILE="secrets.auto.tfvars"

_REQUIRED_VARS="LANGSMITH_PG_PASSWORD LANGSMITH_LICENSE_KEY LANGSMITH_ADMIN_EMAIL"


# ── Prompt helper (skips if env var already set) ──────────────────────────────
# Prompt text goes to stderr: stdout is the return channel for the value, so
# anything printed there is swallowed by the caller's command substitution.
_prompt() {
  local env_var="$1"
  local prompt_text="$2"
  local mode="${3:-}"   # "" = required secret | optional = may be left blank | visible = echo input
  local val="${!env_var:-}"
  if [[ -z "$val" && -t 0 ]]; then
    printf "%s: " "$prompt_text" >&2
    if [[ "$mode" == "visible" ]]; then
      read -r val || val=""   # Ctrl-D / EOF — handled by the empty check below
    else
      read -rs val || val=""
      echo >&2                # -s also swallows the newline the user typed
    fi
  fi
  if [[ -z "$val" && "$mode" != "optional" ]]; then
    echo "ERROR: No value provided for $env_var." >&2
    return 1
  fi
  echo "$val"
}

# ── Non-interactive guard ─────────────────────────────────────────────────────
# A sandboxed shell (Cursor, CI, `make` under a pipe) has no tty, so prompting
# is impossible. Checked here at top level, and reported on stdout: _prompt
# cannot report anything itself because its stdout is captured by the caller,
# and a harness that shows only stdout would otherwise display nothing at all.
if [[ ! -t 0 ]]; then
  _missing=""
  for _v in $_REQUIRED_VARS; do
    [[ -n "${!_v:-}" ]] || _missing="$_missing $_v"
  done
  if [[ -n "$_missing" ]]; then
    echo "ERROR: stdin is not a tty, so setup-env.sh cannot prompt for secrets."
    echo "       Missing:$_missing"
    echo ""
    echo "       Run it from a real terminal, or pre-set the values:"
    for _v in $_missing; do
      echo "         export $_v='<value>'"
    done
    echo ""
    echo "       Then re-run: make setup-env"
    exit 1
  fi
fi

# ── Collect secrets ───────────────────────────────────────────────────────────
echo ""
echo "LangSmith — Terraform input bootstrap"
echo ""
echo "  Passwords are hidden as you type."
echo ""

pg_password=$(_prompt "LANGSMITH_PG_PASSWORD" "PostgreSQL admin password  ")
license_key=$(_prompt "LANGSMITH_LICENSE_KEY" "LangSmith license key      ")
admin_email=$(_prompt "LANGSMITH_ADMIN_EMAIL" "Initial org admin email    " visible)

# ── Write secrets.auto.tfvars ─────────────────────────────────────────────────
cat > "$SECRETS_FILE" << EOF
# Auto-generated by setup-env.sh — DO NOT COMMIT
# Re-run ./setup-env.sh to regenerate.

postgres_admin_password = "$pg_password"
langsmith_license_key   = "$license_key"
langsmith_admin_email   = "$admin_email"
EOF

chmod 600 "$SECRETS_FILE"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "  Wrote $SECRETS_FILE (chmod 600)"
echo ""
echo "Next (from terraform/azure/):"
echo "  make preflight     # verify az login, providers, RBAC"
echo "  make init          # terraform init"
echo "  make apply         # deploy AKS + Postgres + Redis + Blob + Key Vault"
echo "  make seed-secrets  # write LangSmith app secrets into Key Vault"
echo "  make kubeconfig    # fetch AKS credentials"
echo "  make k8s-secrets   # create langsmith-config-secret from Key Vault"
echo "  make init-values   # generate Helm values from Terraform outputs"
echo "  make deploy        # helm upgrade --install langsmith"
