#!/usr/bin/env bash

# MIT License - Copyright (c) 2026 LangChain, Inc.
# NOTICE: Actively being tested and subject to change. Not officially supported by LangChain.

# test-worker.sh — Run one test permutation in an isolated worker environment.
#
# Called by test-orchestrator.sh. Each worker runs in its own git worktree
# with a unique name_prefix so AWS resources don't collide with each other
# or with the user's existing cluster.
#
# Usage (direct):
#   ./infra/scripts/test-worker.sh <perm_number> <name_prefix> <results_dir> [--dry-run]
#
# Required env vars (exported by orchestrator, inherited automatically):
#   WORKER_REGION           — AWS region
#   WORKER_EKS_VERSION      — Kubernetes version (default: 1.31)
#   WORKER_PG_SOURCE        — postgres_source: external|in-cluster (default: external)
#   WORKER_REDIS_SOURCE     — redis_source:    external|in-cluster (default: external)
#   WORKER_DOMAIN           — langsmith_domain  (can be empty)
#   WORKER_LE_EMAIL         — letsencrypt_email (can be empty)
#   WORKER_HOSTED_ZONE      — cert_manager_hosted_zone_id (can be empty)
#
# TF_VAR_* secrets must already be exported (via setup-env.sh) in the calling shell.
#
# The script:
#   1. Writes infra/terraform.tfvars with worker-specific name_prefix
#   2. Runs test-permutations.sh <perm_number> (--dry-run pass-through)
#   3. Writes <results_dir>/p<N>.json with status, duration, and summary

set -euo pipefail
export AWS_PAGER=""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/_common.sh"

# ── Credential hygiene ────────────────────────────────────────────────────────
# AWS_CREDENTIAL_EXPIRATION baked into the parent shell poisons all AWS calls.
# Unset it so every _aws()/_kubectl()/_helm() call reads ~/.aws/credentials freshly.
# hydrate-creds.sh keeps that file up to date — workers never need to rotate creds.
unset AWS_CREDENTIAL_EXPIRATION AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN

# ── Args ──────────────────────────────────────────────────────────────────────

PERM="${1:?usage: test-worker.sh <perm_number> <name_prefix> <results_dir> [--dry-run]}"
NAME_PREFIX="${2:?usage: test-worker.sh <perm_number> <name_prefix> <results_dir> [--dry-run]}"
RESULTS_DIR="${3:?usage: test-worker.sh <perm_number> <name_prefix> <results_dir> [--dry-run]}"
DRY_RUN_FLAG="${4:-}"

# ── Required env vars ─────────────────────────────────────────────────────────

REGION="${WORKER_REGION:?WORKER_REGION env var required (set by orchestrator or manually)}"
EKS_VERSION="${WORKER_EKS_VERSION:-1.31}"
# Workers always use in-cluster Postgres + Redis — test clusters are lightweight
# and short-lived. RDS/ElastiCache per worker would be expensive and slow to spin up.
# The gateway/TLS permutations don't test backend service provisioning.
PG_SOURCE="in-cluster"
REDIS_SOURCE="in-cluster"
DOMAIN="${WORKER_DOMAIN:-}"
LE_EMAIL="${WORKER_LE_EMAIL:-}"
HOSTED_ZONE="${WORKER_HOSTED_ZONE:-}"

# Must be one of: dev|staging|prod|test|uat (variable validation rejects short forms like "t").
# Cluster name will be: <name_prefix>-test-eks  →  e.g. tst1-test-eks
ENVIRONMENT="test"

# init-values.sh requires an admin email — allow override via env var,
# fall back to a test-only placeholder for worker clusters.
export LANGSMITH_ADMIN_EMAIL="${LANGSMITH_ADMIN_EMAIL:-test-worker@langsmith.local}"

# Skip SSM/ESO — test workers have no SSM parameters. Secrets are injected via
# TF_VAR_* / LANGSMITH_* env vars (sourced from setup-env.sh in the calling shell).
export SKIP_ESO=true

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  LangSmith Test Worker — P${PERM}"
echo "  prefix=${NAME_PREFIX}  cluster=${NAME_PREFIX}-${ENVIRONMENT}-eks"
echo "  workdir=$(pwd)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── Generate worker-specific terraform.tfvars ─────────────────────────────────
# Creates a complete, minimal tfvars for a test cluster.
# The user's terraform.tfvars is never read or modified.

cat > "$INFRA_DIR/terraform.tfvars" <<TFVARS
# Auto-generated by test-worker.sh for permutation ${PERM}
# Worker: ${NAME_PREFIX}  cluster: ${NAME_PREFIX}-${ENVIRONMENT}-eks
# DO NOT EDIT — regenerated on each orchestrator run.

name_prefix = "${NAME_PREFIX}"
environment = "${ENVIRONMENT}"
region      = "${REGION}"
owner       = "test-orchestrator"

#── Networking ────────────────────────────────────────────────────────────────
create_vpc                = true
enable_public_eks_cluster = true

#── EKS ───────────────────────────────────────────────────────────────────────
eks_cluster_version = "${EKS_VERSION}"

eks_managed_node_groups = {
  default = {
    name           = "node-group-default"
    instance_types = ["m5.2xlarge"]
    min_size       = 2
    max_size       = 5
  }
}
create_gp3_storage_class = true

#── Backend Services ──────────────────────────────────────────────────────────
postgres_source   = "${PG_SOURCE}"
redis_source      = "${REDIS_SOURCE}"
clickhouse_source = "in-cluster"

#── Namespace & Sizing ────────────────────────────────────────────────────────
langsmith_namespace = "langsmith"
sizing_profile      = "dev"

#── Features (all off for test clusters) ─────────────────────────────────────
enable_deployments   = false
enable_agent_builder = false
enable_insights      = false
enable_polly         = false

#── Gateway / TLS — set per permutation by test-permutations.sh override ─────
enable_envoy_gateway     = false
enable_istio_gateway     = false
tls_certificate_source   = "none"
create_cert_manager_irsa = false
TFVARS

# Append optional vars only when non-empty (prevents empty-string validation errors)
[[ -n "$DOMAIN" ]]      && echo "langsmith_domain            = \"${DOMAIN}\""      >> "$INFRA_DIR/terraform.tfvars"
[[ -n "$LE_EMAIL" ]]    && echo "letsencrypt_email           = \"${LE_EMAIL}\""    >> "$INFRA_DIR/terraform.tfvars"
[[ -n "$HOSTED_ZONE" ]] && echo "cert_manager_hosted_zone_id = \"${HOSTED_ZONE}\"" >> "$INFRA_DIR/terraform.tfvars"

echo "  Generated terraform.tfvars for ${NAME_PREFIX}-${ENVIRONMENT}-eks"

# ── Run the permutation ───────────────────────────────────────────────────────

mkdir -p "$RESULTS_DIR"

START_TS=$(date +%s)

set +e
"$SCRIPT_DIR/test-permutations.sh" "$PERM" $DRY_RUN_FLAG
EXIT_CODE=$?
set -e

END_TS=$(date +%s)
DURATION=$(( END_TS - START_TS ))

# ── Determine pass/fail from exit code and summary log ───────────────────────

STATUS="failed"
[[ $EXIT_CODE -eq 0 ]] && STATUS="passed"

# Parse the last summary line written by test-permutations.sh
SUMMARY_LOG="$INFRA_DIR/logs/summary.log"
LAST_SUMMARY=""
if [[ -f "$SUMMARY_LOG" ]]; then
  LAST_SUMMARY=$(tail -1 "$SUMMARY_LOG" 2>/dev/null || echo "")
fi

# ── Write JSON result ─────────────────────────────────────────────────────────
# Consumed by test-orchestrator.sh to build the grand summary table.

RESULT_FILE="$RESULTS_DIR/p${PERM}.json"

# Escape the summary string for JSON
SUMMARY_ESCAPED=$(echo "$LAST_SUMMARY" | sed 's/\\/\\\\/g; s/"/\\"/g')

cat > "$RESULT_FILE" <<JSON
{
  "permutation":      ${PERM},
  "name_prefix":      "${NAME_PREFIX}",
  "cluster_name":     "${NAME_PREFIX}-${ENVIRONMENT}-eks",
  "status":           "${STATUS}",
  "exit_code":        ${EXIT_CODE},
  "duration_seconds": ${DURATION},
  "summary":          "${SUMMARY_ESCAPED}",
  "log":              "${RESULTS_DIR}/p${PERM}-worker.log"
}
JSON

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  P${PERM} $(echo "$STATUS" | tr '[:lower:]' '[:upper:]')  duration=${DURATION}s  result=${RESULT_FILE}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

exit $EXIT_CODE
