#!/usr/bin/env bash

# MIT License - Copyright (c) 2026 LangChain, Inc.
# NOTICE: Actively being tested and subject to change. Not officially supported by LangChain.
# See LICENSE at the root of this repository for full license text.

# test-permutations.sh — Cycles through all cert-manager / gateway / TLS permutations.
#
# Each permutation writes a permutation.auto.tfvars that overrides ONLY the
# gateway/TLS variables — your terraform.tfvars (cluster, RDS, Redis, etc.)
# is never touched. Terraform's auto.tfvars load-order guarantees these
# overrides win.
#
# Usage:
#   ./infra/scripts/test-permutations.sh           # run all permutations
#   ./infra/scripts/test-permutations.sh 5         # run one permutation
#   ./infra/scripts/test-permutations.sh 5 6 7     # run a subset
#   ./infra/scripts/test-permutations.sh --dry-run # show plan only, no apply
#   ./infra/scripts/test-permutations.sh --skip-destroy 5  # skip destroy phase
#
# Permutations:
#   1  ALB only         tls=none
#   2  ALB + ACM        tls=acm  (needs langsmith_domain + NS delegation)
#   3  ALB + Let's Encrypt HTTP-01  tls=letsencrypt  (needs domain)
#   4  Istio Gateway    tls=none  (no TLS)
#   5  Istio + Let's Encrypt DNS-01 via Route 53 IRSA  (full cert-manager path)
#   6  Istio + DNS-01 domain change  (validate stale-secret deletion + re-issuance)
#   7  terraform destroy with DNS-01 active  (validate destroy provisioners)
#   8  Envoy Gateway    tls=none  (no TLS — validates feat/aws-envoy code path)
#
# Prerequisites (set in terraform.tfvars before running):
#   - name_prefix, environment, region
#   - postgres_source, redis_source (external or in-cluster)
#   - For permutations 2-6: langsmith_domain (must be Route 53 delegated)
#   - For permutations 2, 3, 5, 6: letsencrypt_email
#   - For permutations 5, 6, 7: cert_manager_hosted_zone_id
#   - For permutations 2-7: domain must be Route 53 NS-delegated
#
# Log files:
#   Each run writes full output to logs/permutation-<N>-<timestamp>/
#   Summary is printed to stdout and appended to logs/summary.log

set -euo pipefail
export AWS_PAGER=""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$SCRIPT_DIR/.."
AWS_DIR="$INFRA_DIR/.."
HELM_DIR="$AWS_DIR/helm"
source "$SCRIPT_DIR/_common.sh"

OVERRIDE_FILE="$INFRA_DIR/permutation.auto.tfvars"
LOG_DIR="$SCRIPT_DIR/../logs"
SUMMARY_LOG="$LOG_DIR/summary.log"
ISTIO_VERSION="${ISTIO_VERSION:-1.24.3}"

# ── Arg parsing ───────────────────────────────────────────────────────────────

DRY_RUN=false
SKIP_DESTROY=false
RUN_ALL=false
SELECTED=()

for arg in "$@"; do
  case "$arg" in
    --dry-run)       DRY_RUN=true ;;
    --skip-destroy)  SKIP_DESTROY=true ;;
    all|"")          RUN_ALL=true ;;
    [1-8])           SELECTED+=("$arg") ;;
    *)               echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

[[ ${#SELECTED[@]} -eq 0 ]] && RUN_ALL=true

# ── Validate prerequisites ────────────────────────────────────────────────────

if [[ ! -f "$INFRA_DIR/terraform.tfvars" ]]; then
  echo "ERROR: terraform.tfvars not found. Copy terraform.tfvars.example and fill it in." >&2
  exit 1
fi

_region=$(_parse_tfvar "region") || { echo "ERROR: region not set in terraform.tfvars" >&2; exit 1; }
_name_prefix=$(_parse_tfvar "name_prefix") || { echo "ERROR: name_prefix not set in terraform.tfvars" >&2; exit 1; }
_environment=$(_parse_tfvar "environment") || { echo "ERROR: environment not set in terraform.tfvars" >&2; exit 1; }
_domain=$(_parse_tfvar "langsmith_domain") || _domain=""
_le_email=$(_parse_tfvar "letsencrypt_email") || _le_email=""
_hosted_zone=$(_parse_tfvar "cert_manager_hosted_zone_id") || _hosted_zone=""

_cluster_name="${_name_prefix}-${_environment}-eks"

mkdir -p "$LOG_DIR"

# ── Helpers ───────────────────────────────────────────────────────────────────

_section() { echo ""; printf '\033[1m══ %s ══\033[0m\n' "$1"; echo ""; }
_step()    { printf '  \033[0;36m→\033[0m  %s\n' "$1"; }
_ok()      { printf '  \033[32m✔\033[0m  %s\n' "$1"; }
_err()     { printf '  \033[31m✘\033[0m  %s\n' "$1"; }
_warn()    { printf '  \033[33m⚠\033[0m  %s\n' "$1"; }

_run() {
  # _run <log_file> <description> <cmd...>
  local logfile="$1"; shift
  local desc="$1"; shift
  _step "$desc"
  if [[ "$DRY_RUN" == "true" ]]; then
    echo "    [dry-run] would run: $*" | tee -a "$logfile"
    return 0
  fi
  if "$@" >> "$logfile" 2>&1; then
    _ok "$desc"
    return 0
  else
    local rc=$?
    _err "$desc (exit $rc — see $logfile)"
    return $rc
  fi
}

_write_override() {
  # Write permutation.auto.tfvars with the given content.
  # Terraform loads *.auto.tfvars after terraform.tfvars — these vars win.
  local content="$1"
  cat > "$OVERRIDE_FILE" <<EOF
# Auto-generated by test-permutations.sh — DO NOT EDIT MANUALLY
# Override file for permutation testing. Deleted after each run.
$content
EOF
  _step "Wrote permutation.auto.tfvars"
  [[ "$DRY_RUN" == "true" ]] && cat "$OVERRIDE_FILE" | sed 's/^/    /'
}

_cleanup_override() {
  rm -f "$OVERRIDE_FILE"
}

_tf() {
  # Run terraform in INFRA_DIR
  terraform -chdir="$INFRA_DIR" "$@"
}

_kubeconfig() {
  _step "Updating kubeconfig for $_cluster_name"
  [[ "$DRY_RUN" == "true" ]] && return 0
  aws eks update-kubeconfig --name "$_cluster_name" --region "$_region" >/dev/null 2>&1
}

_helm_uninstall() {
  local logfile="$1"
  _step "Uninstalling Helm releases (langsmith, langgraph-dataplane)"
  [[ "$DRY_RUN" == "true" ]] && return 0
  {
    helm uninstall langsmith -n langsmith 2>/dev/null || true
    helm uninstall langgraph-dataplane -n langsmith-agents 2>/dev/null || true
    # Wait for namespace to drain before destroy
    kubectl delete namespace langsmith langsmith-agents 2>/dev/null || true
    kubectl wait --for=delete namespace/langsmith --timeout=120s 2>/dev/null || true
  } >> "$logfile" 2>&1
}

_tf_destroy() {
  local logfile="$1"
  [[ "$SKIP_DESTROY" == "true" ]] && { _warn "Skipping destroy (--skip-destroy)"; return 0; }
  _step "terraform destroy -auto-approve"
  [[ "$DRY_RUN" == "true" ]] && return 0

  # Pre-remove k8s-provider resources from state before destroying AWS infra.
  # When EKS nodes drain during destroy, the kubernetes/helm providers lose
  # connectivity and cause Terraform to error on Helm releases and k8s resources
  # even though the underlying AWS resources are already gone. Removing them from
  # state first lets terraform destroy proceed cleanly against just the AWS layer.
  local _k8s_resources
  _k8s_resources=$(_tf state list 2>/dev/null | grep -E \
    "helm_release\.|kubernetes_namespace\.|kubernetes_storage_class\.|kubernetes_secret\.|terraform_data\.letsencrypt|terraform_data\.istio|time_sleep\." || true)
  if [[ -n "$_k8s_resources" ]]; then
    _warn "Pre-removing k8s-provider state entries to avoid connectivity errors during destroy"
    echo "$_k8s_resources" | xargs -I{} _tf state rm "{}" >> "$logfile" 2>&1 || true
  fi

  _tf destroy -auto-approve >> "$logfile" 2>&1
  _ok "Infrastructure destroyed"
}

_tf_apply() {
  local logfile="$1"
  _step "terraform apply -auto-approve"
  [[ "$DRY_RUN" == "true" ]] && return 0
  _tf init -upgrade >> "$logfile" 2>&1
  _tf apply -auto-approve >> "$logfile" 2>&1
  _ok "Infrastructure applied"
}

_helm_deploy() {
  local logfile="$1"
  _step "init-values + helm deploy"
  [[ "$DRY_RUN" == "true" ]] && return 0
  "$HELM_DIR/scripts/init-values.sh" >> "$logfile" 2>&1
  "$HELM_DIR/scripts/deploy.sh" >> "$logfile" 2>&1
  _ok "LangSmith deployed"
}

# ── Istio install/uninstall helpers ───────────────────────────────────────────

_istio_install() {
  local logfile="$1"
  _step "Installing Istio $ISTIO_VERSION (istiod + ingressgateway)"
  [[ "$DRY_RUN" == "true" ]] && return 0
  {
    helm repo add istio https://istio-release.storage.googleapis.com/charts --force-update
    helm repo update
    helm upgrade --install istio-base istio/base \
      --namespace istio-system --create-namespace --version "$ISTIO_VERSION" --wait
    helm upgrade --install istiod istio/istiod \
      --namespace istio-system --version "$ISTIO_VERSION" --wait
    # Install ingressgateway on public subnets (internet-facing NLB)
    _public_subnets=$(aws ec2 describe-subnets \
      --region "$_region" \
      --filters "Name=tag:kubernetes.io/cluster/${_cluster_name},Values=shared,owned" \
                "Name=mapPublicIpOnLaunch,Values=true" \
      --query 'Subnets[*].SubnetId' \
      --output text | tr '\t\n' ',,' | sed 's/,*$//' | sed 's/,/\\,/g')
    if [[ -n "$_public_subnets" ]]; then
      helm upgrade --install istio-ingressgateway istio/gateway \
        --namespace istio-system --version "$ISTIO_VERSION" \
        --skip-schema-validation \
        --set "service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-scheme=internet-facing" \
        --set "service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-subnets=${_public_subnets}" \
        --wait
    else
      helm upgrade --install istio-ingressgateway istio/gateway \
        --namespace istio-system --version "$ISTIO_VERSION" \
        --skip-schema-validation --wait
    fi
  } >> "$logfile" 2>&1
  _ok "Istio installed"
}

_istio_uninstall() {
  local logfile="$1"
  _step "Uninstalling Istio"
  [[ "$DRY_RUN" == "true" ]] && return 0
  {
    helm uninstall istio-ingressgateway -n istio-system 2>/dev/null || true
    helm uninstall istiod -n istio-system 2>/dev/null || true
    helm uninstall istio-base -n istio-system 2>/dev/null || true
    kubectl delete namespace istio-system 2>/dev/null || true
    kubectl wait --for=delete namespace/istio-system --timeout=120s 2>/dev/null || true
  } >> "$logfile" 2>&1
  _ok "Istio uninstalled"
}

_istio_gateway_http() {
  # Create an HTTP-only Istio Gateway in the langsmith namespace.
  local domain="$1"
  local logfile="$2"
  _step "Creating Istio Gateway (HTTP-only) for $domain"
  [[ "$DRY_RUN" == "true" ]] && return 0
  kubectl apply -f - >> "$logfile" 2>&1 <<EOF
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: langsmith-gateway
  namespace: langsmith
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "${domain}"
EOF
  _ok "Istio Gateway created"
}

_nlb_hostname() {
  kubectl get svc istio-ingressgateway -n istio-system \
    -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo ""
}

# ── Assertion helpers ─────────────────────────────────────────────────────────

_PASS=0
_FAIL=0
_RESULTS=()

_assert() {
  local name="$1"
  local ok="$2"
  local detail="${3:-}"
  if [[ "$ok" == "true" ]]; then
    _PASS=$((_PASS + 1))
    _RESULTS+=("  ✔  $name")
  else
    _FAIL=$((_FAIL + 1))
    _RESULTS+=("  ✗  $name${detail:+  ($detail)}")
  fi
}

_reset_results() { _PASS=0; _FAIL=0; _RESULTS=(); }

_assert_http() {
  local name="$1"
  local url="$2"
  local expected="${3:-200}"
  local code
  code=$(curl -sk -o /dev/null -w "%{http_code}" --max-time 15 "$url" 2>/dev/null || echo "000")
  [[ "$code" == "$expected" ]] \
    && _assert "$name" true "HTTP $code" \
    || _assert "$name" false "expected $expected, got $code"
}

_assert_tls_issuer() {
  local name="$1"
  local url="$2"
  local expect_pattern="$3"
  local issuer
  issuer=$(curl -sv --max-time 10 "$url" 2>&1 | grep -i "issuer:" | head -1 || echo "")
  if echo "$issuer" | grep -qi "$expect_pattern"; then
    _assert "$name" true "$issuer"
  else
    _assert "$name" false "issuer '$issuer' does not match '$expect_pattern'"
  fi
}

_assert_k8s() {
  local name="$1"
  local cmd="$2"
  local expected="$3"
  local actual
  actual=$(eval "$cmd" 2>/dev/null || echo "")
  [[ "$actual" == "$expected" ]] \
    && _assert "$name" true \
    || _assert "$name" false "expected '$expected', got '$actual'"
}

_assert_k8s_exists() {
  local name="$1"
  local cmd="$2"
  local result
  result=$(eval "$cmd" 2>/dev/null || echo "")
  [[ -n "$result" ]] \
    && _assert "$name" true \
    || _assert "$name" false "not found"
}

_assert_k8s_absent() {
  local name="$1"
  local cmd="$2"
  local result
  result=$(eval "$cmd" 2>/dev/null || echo "")
  [[ -z "$result" ]] \
    && _assert "$name" true \
    || _assert "$name" false "expected absent, found: $result"
}

_print_results() {
  local perm_name="$1"
  local ts="$2"
  echo ""
  printf '\033[1m── Results: %s ──\033[0m\n' "$perm_name"
  for r in "${_RESULTS[@]}"; do echo "$r"; done
  echo ""
  if [[ $_FAIL -eq 0 ]]; then
    printf '  \033[32mPASSED\033[0m  %d/%d tests\n' "$_PASS" "$((_PASS + _FAIL))"
    echo "  PASSED  $_PASS/$((_PASS+_FAIL))  [$perm_name]  $ts" >> "$SUMMARY_LOG"
  else
    printf '  \033[31mFAILED\033[0m  %d/%d tests (%d passed)\n' "$_FAIL" "$((_PASS+_FAIL))" "$_PASS"
    echo "  FAILED  $_FAIL/$((_PASS+_FAIL)) failed  [$perm_name]  $ts" >> "$SUMMARY_LOG"
    for r in "${_RESULTS[@]}"; do
      echo "$r" >> "$SUMMARY_LOG"
    done
  fi
  echo ""
}

# ── Permutation definitions ───────────────────────────────────────────────────

run_1() {
  local name="P1: ALB + tls=none"
  local ts; ts=$(date +%Y%m%d-%H%M%S)
  local logdir="$LOG_DIR/p1-alb-none-$ts"
  mkdir -p "$logdir"
  local log="$logdir/run.log"
  _reset_results

  _section "$name"

  _write_override 'tls_certificate_source  = "none"
enable_envoy_gateway    = false
enable_istio_gateway    = false
create_cert_manager_irsa = false'

  _helm_uninstall "$log"
  _tf_destroy "$log"
  _tf_apply "$log"
  _kubeconfig
  _helm_deploy "$log"

  # Assertions
  _step "Running assertions..."
  local alb_host
  alb_host=$(_tf output -raw alb_dns_name 2>/dev/null || echo "")
  _assert "ALB hostname from TF output" "$([[ -n "$alb_host" ]] && echo true || echo false)"

  _assert_http "GET http://${alb_host}/api/v1/health → 200" "http://${alb_host}/api/v1/health"
  _assert_http "GET http://${alb_host}/ → 200 (frontend)" "http://${alb_host}/" "200"

  # No TLS — ALB should not redirect
  local redirect
  redirect=$(curl -so /dev/null -w "%{http_code}" --max-time 10 "http://${alb_host}/" 2>/dev/null || echo "000")
  _assert "ALB: no HTTPS redirect (tls=none)" "$([[ "$redirect" != "301" && "$redirect" != "308" ]] && echo true || echo false)" "got $redirect"

  _assert_k8s_absent "No ClusterIssuer letsencrypt-prod" \
    "kubectl get clusterissuer letsencrypt-prod -o name 2>/dev/null"

  _print_results "$name" "$ts"
}

run_2() {
  local name="P2: ALB + ACM TLS"
  local ts; ts=$(date +%Y%m%d-%H%M%S)
  local logdir="$LOG_DIR/p2-alb-acm-$ts"
  mkdir -p "$logdir"
  local log="$logdir/run.log"
  _reset_results

  _section "$name"

  if [[ -z "$_domain" ]]; then
    _warn "Skipping $name — langsmith_domain not set in terraform.tfvars"
    return 0
  fi

  _write_override "tls_certificate_source  = \"acm\"
langsmith_domain        = \"${_domain}\"
enable_envoy_gateway    = false
enable_istio_gateway    = false
create_cert_manager_irsa = false"

  _helm_uninstall "$log"
  _tf_destroy "$log"
  _tf_apply "$log"
  _kubeconfig
  _helm_deploy "$log"

  _step "Running assertions..."
  _assert_http "GET https://${_domain}/api/v1/health → 200" "https://${_domain}/api/v1/health"
  _assert_tls_issuer "ACM cert issued by Amazon" "https://${_domain}" "Amazon"

  local redirect
  redirect=$(curl -so /dev/null -w "%{http_code}" --max-time 10 "http://${_domain}/" 2>/dev/null || echo "000")
  _assert "ALB: HTTP → HTTPS redirect (301/308)" "$([[ "$redirect" == "301" || "$redirect" == "308" ]] && echo true || echo false)" "got $redirect"

  _assert_k8s_absent "No ClusterIssuer letsencrypt-prod" \
    "kubectl get clusterissuer letsencrypt-prod -o name 2>/dev/null"

  _print_results "$name" "$ts"
}

run_3() {
  local name="P3: ALB + Let's Encrypt HTTP-01"
  local ts; ts=$(date +%Y%m%d-%H%M%S)
  local logdir="$LOG_DIR/p3-alb-http01-$ts"
  mkdir -p "$logdir"
  local log="$logdir/run.log"
  _reset_results

  _section "$name"

  if [[ -z "$_domain" || -z "$_le_email" ]]; then
    _warn "Skipping $name — langsmith_domain or letsencrypt_email not set"
    return 0
  fi

  _write_override "tls_certificate_source  = \"letsencrypt\"
langsmith_domain        = \"${_domain}\"
letsencrypt_email       = \"${_le_email}\"
enable_envoy_gateway    = false
enable_istio_gateway    = false
create_cert_manager_irsa = false"

  _helm_uninstall "$log"
  _tf_destroy "$log"
  _tf_apply "$log"
  _kubeconfig
  _helm_deploy "$log"

  _step "Running assertions..."
  _assert_k8s "ClusterIssuer letsencrypt-prod exists" \
    "kubectl get clusterissuer letsencrypt-prod -o jsonpath='{.metadata.name}'" \
    "letsencrypt-prod"
  _assert_k8s "ClusterIssuer uses http01 solver" \
    "kubectl get clusterissuer letsencrypt-prod -o jsonpath='{.spec.acme.solvers[0].http01.ingress.ingressClassName}'" \
    "alb"
  # Wait up to 5 min for cert
  _step "Waiting for Let's Encrypt certificate (HTTP-01, up to 5 min)..."
  for i in $(seq 1 30); do
    local ready
    ready=$(kubectl get certificate -n langsmith -o jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "")
    [[ "$ready" == "True" ]] && break
    sleep 10
  done
  local cert_ready
  cert_ready=$(kubectl get certificate -n langsmith -o jsonpath='{.items[0].status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "")
  _assert "Let's Encrypt cert READY=True" "$([[ "$cert_ready" == "True" ]] && echo true || echo false)"

  _assert_http "GET https://${_domain}/api/v1/health → 200" "https://${_domain}/api/v1/health"
  _assert_tls_issuer "LE cert issued by Let's Encrypt" "https://${_domain}" "Let's Encrypt"

  _print_results "$name" "$ts"
}

run_4() {
  local name="P4: Istio Gateway + tls=none"
  local ts; ts=$(date +%Y%m%d-%H%M%S)
  local logdir="$LOG_DIR/p4-istio-none-$ts"
  mkdir -p "$logdir"
  local log="$logdir/run.log"
  _reset_results

  _section "$name"

  if [[ -z "$_domain" ]]; then
    _warn "Skipping $name — langsmith_domain not set (needed for Istio Gateway hosts field)"
    return 0
  fi

  _write_override "tls_certificate_source  = \"none\"
langsmith_domain        = \"${_domain}\"
enable_envoy_gateway    = false
enable_istio_gateway    = true
create_cert_manager_irsa = false"

  _helm_uninstall "$log"
  _istio_uninstall "$log"
  _tf_destroy "$log"
  _tf_apply "$log"
  _kubeconfig
  _istio_install "$log"
  _istio_gateway_http "$_domain" "$log"
  _helm_deploy "$log"

  _step "Running assertions..."
  _assert_k8s "istiod deployment ready" \
    "kubectl get deployment istiod -n istio-system -o jsonpath='{.status.readyReplicas}'" \
    "$(kubectl get deployment istiod -n istio-system -o jsonpath='{.spec.replicas}' 2>/dev/null || echo "1")"

  local nlb_host
  nlb_host=$(_nlb_hostname)
  _assert "istio-ingressgateway has NLB hostname" "$([[ -n "$nlb_host" ]] && echo true || echo false)" "$nlb_host"

  _assert_k8s "Gateway langsmith-gateway exists" \
    "kubectl get gateway langsmith-gateway -n langsmith -o jsonpath='{.metadata.name}'" \
    "langsmith-gateway"
  _assert_k8s "Gateway HTTP-only (no HTTPS)" \
    "kubectl get gateway langsmith-gateway -n langsmith -o jsonpath='{.spec.servers[?(@.port.number==443)].port.name}'" \
    ""

  _assert_http "GET http://${nlb_host}/api/v1/health → 200" "http://${nlb_host}/api/v1/health"

  _assert_k8s_absent "No ClusterIssuer letsencrypt-prod" \
    "kubectl get clusterissuer letsencrypt-prod -o name 2>/dev/null"
  _assert_k8s_absent "No TLS secret in istio-system" \
    "kubectl get secret langsmith-tls -n istio-system -o name 2>/dev/null"

  _print_results "$name" "$ts"
}

run_5() {
  local name="P5: Istio + Let's Encrypt DNS-01 (Route 53 IRSA)"
  local ts; ts=$(date +%Y%m%d-%H%M%S)
  local logdir="$LOG_DIR/p5-istio-dns01-$ts"
  mkdir -p "$logdir"
  local log="$logdir/run.log"
  _reset_results

  _section "$name"

  if [[ -z "$_domain" || -z "$_le_email" || -z "$_hosted_zone" ]]; then
    _warn "Skipping $name — langsmith_domain, letsencrypt_email, or cert_manager_hosted_zone_id not set"
    return 0
  fi

  _write_override "tls_certificate_source   = \"none\"
langsmith_domain         = \"${_domain}\"
letsencrypt_email        = \"${_le_email}\"
enable_envoy_gateway     = false
enable_istio_gateway     = true
create_cert_manager_irsa = true
cert_manager_hosted_zone_id = \"${_hosted_zone}\""

  _helm_uninstall "$log"
  _istio_uninstall "$log"
  _tf_destroy "$log"
  _tf_apply "$log"
  _kubeconfig
  _istio_install "$log"
  # Taint Certificate + Gateway resources so pass 2 recreates them.
  # Required because _istio_uninstall removes istio-system (deleting the
  # Certificate/Gateway Kubernetes objects) but terraform state still marks
  # these terraform_data resources as current — without a taint they won't re-run.
  if [[ "$DRY_RUN" != "true" ]]; then
    _step "Tainting Certificate + Gateway resources for pass 2"
    _cert_res=$(_tf state list 2>/dev/null | grep "terraform_data.langsmith_certificate" || echo "")
    _gw_res=$(_tf state list 2>/dev/null | grep "terraform_data.istio_gateway_tls" || echo "")
    [[ -n "$_cert_res" ]] && terraform -chdir="$INFRA_DIR" taint "$_cert_res" 2>/dev/null || true
    [[ -n "$_gw_res" ]] && terraform -chdir="$INFRA_DIR" taint "$_gw_res" 2>/dev/null || true
    _ok "Resources tainted for pass 2"
  fi
  # NOTE: The Certificate and Gateway terraform_data provisioners require istio-system
  # to exist. They are tainted above so pass 2 re-runs them with Istio now ready.
  _step "terraform apply (pass 2 — Certificate + Gateway provisioners)"
  [[ "$DRY_RUN" != "true" ]] && _tf apply -auto-approve >> "$log" 2>&1 && _ok "Pass 2 applied"
  _helm_deploy "$log"

  _step "Running assertions..."

  # IAM assertions
  local irsa_arn
  irsa_arn=$(_tf output -raw cert_manager_irsa_role_arn 2>/dev/null || echo "")
  _assert "cert-manager IRSA role ARN in TF output" "$([[ -n "$irsa_arn" ]] && echo true || echo false)" "$irsa_arn"

  local role_name="${_cluster_name}-cert-manager"
  _assert_k8s_exists "cert-manager IAM role exists in AWS" \
    "aws iam get-role --role-name $role_name --query 'Role.RoleName' --output text 2>/dev/null"

  # cert-manager assertions
  _assert_k8s "cert-manager SA annotated with IRSA role" \
    "kubectl get sa cert-manager -n cert-manager -o jsonpath='{.metadata.annotations.eks\.amazonaws\.com/role-arn}'" \
    "$irsa_arn"

  _assert_k8s "ClusterIssuer letsencrypt-prod exists" \
    "kubectl get clusterissuer letsencrypt-prod -o jsonpath='{.metadata.name}'" \
    "letsencrypt-prod"
  _assert_k8s "ClusterIssuer uses dns01/route53 solver" \
    "kubectl get clusterissuer letsencrypt-prod -o jsonpath='{.spec.acme.solvers[0].dns01.route53.hostedZoneID}'" \
    "$_hosted_zone"

  # Certificate assertions
  _assert_k8s "Certificate langsmith-tls exists in istio-system" \
    "kubectl get certificate langsmith-tls -n istio-system -o jsonpath='{.metadata.name}'" \
    "langsmith-tls"
  local cert_ready
  cert_ready=$(kubectl get certificate langsmith-tls -n istio-system \
    -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "")
  _assert "Certificate langsmith-tls READY=True" "$([[ "$cert_ready" == "True" ]] && echo true || echo false)" "status=$cert_ready"

  _assert_k8s_exists "TLS secret langsmith-tls in istio-system" \
    "kubectl get secret langsmith-tls -n istio-system -o name 2>/dev/null"

  # Gateway assertions
  _assert_k8s "Gateway has HTTPS listener (port 443)" \
    "kubectl get gateway langsmith-gateway -n langsmith -o jsonpath='{.spec.servers[?(@.port.number==443)].port.name}'" \
    "https"
  _assert_k8s "Gateway uses credentialName langsmith-tls" \
    "kubectl get gateway langsmith-gateway -n langsmith -o jsonpath='{.spec.servers[?(@.port.number==443)].tls.credentialName}'" \
    "langsmith-tls"
  _assert_k8s "Gateway HTTP listener has httpsRedirect=true" \
    "kubectl get gateway langsmith-gateway -n langsmith -o jsonpath='{.spec.servers[?(@.port.number==80)].tls.httpsRedirect}'" \
    "true"

  # Traffic assertions
  _assert_http "GET https://${_domain}/api/v1/health → 200" "https://${_domain}/api/v1/health"
  _assert_http "GET http://${_domain}/ → 301 HTTPS redirect" "http://${_domain}/" "301"
  _assert_tls_issuer "TLS cert issued by Let's Encrypt" "https://${_domain}" "Let's Encrypt"

  # SAN check
  local cert_san
  cert_san=$(openssl s_client -connect "${_domain}:443" -servername "$_domain" </dev/null 2>/dev/null \
    | openssl x509 -noout -text 2>/dev/null | grep -A1 "Subject Alternative Name" | tail -1 || echo "")
  _assert "TLS cert SAN matches domain" "$([[ "$cert_san" == *"$_domain"* ]] && echo true || echo false)" "$cert_san"

  _print_results "$name" "$ts"
}

run_6() {
  local name="P6: Istio + DNS-01 domain change (stale-secret cleanup)"
  local ts; ts=$(date +%Y%m%d-%H%M%S)
  local logdir="$LOG_DIR/p6-istio-domain-change-$ts"
  mkdir -p "$logdir"
  local log="$logdir/run.log"
  _reset_results

  _section "$name"

  if [[ -z "$_domain" || -z "$_le_email" || -z "$_hosted_zone" ]]; then
    _warn "Skipping $name — requires langsmith_domain, letsencrypt_email, cert_manager_hosted_zone_id"
    return 0
  fi

  # Derive an alt domain by prepending "alt." — assumes same Route 53 zone
  local _alt_domain="alt.${_domain}"
  _warn "This permutation applies with domain=${_domain} then changes to alt-domain=${_alt_domain}"
  _warn "The alt domain must be in the same Route 53 zone: ${_hosted_zone}"

  _step "Phase A: initial apply with ${_domain}"
  _write_override "tls_certificate_source   = \"none\"
langsmith_domain         = \"${_domain}\"
letsencrypt_email        = \"${_le_email}\"
enable_envoy_gateway     = false
enable_istio_gateway     = true
create_cert_manager_irsa = true
cert_manager_hosted_zone_id = \"${_hosted_zone}\""

  _helm_uninstall "$log"
  _istio_uninstall "$log"
  _tf_destroy "$log"
  _tf_apply "$log"
  _kubeconfig
  _istio_install "$log"
  _helm_deploy "$log"

  # Verify initial cert
  local initial_san
  initial_san=$(kubectl get certificate langsmith-tls -n istio-system \
    -o jsonpath='{.spec.dnsNames[0]}' 2>/dev/null || echo "")
  _assert "Phase A: cert SAN is ${_domain}" "$([[ "$initial_san" == "$_domain" ]] && echo true || echo false)" "$initial_san"

  local old_secret_uid
  old_secret_uid=$(kubectl get secret langsmith-tls -n istio-system \
    -o jsonpath='{.metadata.uid}' 2>/dev/null || echo "")
  _assert "Phase A: TLS secret exists" "$([[ -n "$old_secret_uid" ]] && echo true || echo false)"

  _step "Phase B: changing domain to ${_alt_domain}"
  _write_override "tls_certificate_source   = \"none\"
langsmith_domain         = \"${_alt_domain}\"
letsencrypt_email        = \"${_le_email}\"
enable_envoy_gateway     = false
enable_istio_gateway     = true
create_cert_manager_irsa = true
cert_manager_hosted_zone_id = \"${_hosted_zone}\""

  # Re-apply — triggers_replace on langsmith_domain causes re-run of cert + gateway resources
  if [[ "$DRY_RUN" != "true" ]]; then
    _tf apply -auto-approve >> "$log" 2>&1
    _ok "Re-applied with new domain"
  fi

  # Verify old secret was deleted (uid changed = new cert issued)
  _step "Waiting for new certificate (up to 5 min)..."
  for i in $(seq 1 30); do
    local ready
    ready=$(kubectl get certificate langsmith-tls -n istio-system \
      -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "")
    [[ "$ready" == "True" ]] && break
    sleep 10
  done

  local new_san
  new_san=$(kubectl get certificate langsmith-tls -n istio-system \
    -o jsonpath='{.spec.dnsNames[0]}' 2>/dev/null || echo "")
  _assert "Phase B: cert SAN updated to ${_alt_domain}" "$([[ "$new_san" == "$_alt_domain" ]] && echo true || echo false)" "$new_san"

  local new_secret_uid
  new_secret_uid=$(kubectl get secret langsmith-tls -n istio-system \
    -o jsonpath='{.metadata.uid}' 2>/dev/null || echo "")
  _assert "Phase B: TLS secret is a new object (old deleted)" \
    "$([[ "$new_secret_uid" != "$old_secret_uid" ]] && echo true || echo false)" \
    "old=$old_secret_uid new=$new_secret_uid"

  local cert_ready
  cert_ready=$(kubectl get certificate langsmith-tls -n istio-system \
    -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || echo "")
  _assert "Phase B: new cert READY=True" "$([[ "$cert_ready" == "True" ]] && echo true || echo false)"

  _assert_k8s "Gateway updated to new domain host" \
    "kubectl get gateway langsmith-gateway -n langsmith -o jsonpath='{.spec.servers[0].hosts[0]}'" \
    "$_alt_domain"

  _print_results "$name" "$ts"
}

run_7() {
  local name="P7: terraform destroy with DNS-01 active (no orphaned resources)"
  local ts; ts=$(date +%Y%m%d-%H%M%S)
  local logdir="$LOG_DIR/p7-destroy-dns01-$ts"
  mkdir -p "$logdir"
  local log="$logdir/run.log"
  _reset_results

  _section "$name"

  if [[ -z "$_domain" || -z "$_le_email" || -z "$_hosted_zone" ]]; then
    _warn "Skipping $name — requires langsmith_domain, letsencrypt_email, cert_manager_hosted_zone_id"
    return 0
  fi

  # P7 is self-contained: it sets up DNS-01 from scratch, then destroys and
  # verifies no orphaned resources remain.
  #
  # The destroy provisioners on terraform_data resources (ClusterIssuer,
  # Certificate, Gateway) only fire when Terraform has those resources in
  # state. This requires a full apply in THIS worktree before destroy — we
  # cannot rely on state from a prior run or a different worktree (BUG-06).
  _write_override "tls_certificate_source   = \"none\"
langsmith_domain         = \"${_domain}\"
letsencrypt_email        = \"${_le_email}\"
enable_envoy_gateway     = false
enable_istio_gateway     = true
create_cert_manager_irsa = true
cert_manager_hosted_zone_id = \"${_hosted_zone}\""

  _step "Phase 1: Apply infrastructure with DNS-01 (populates state for destroy)..."
  _helm_uninstall "$log"
  _istio_uninstall "$log"
  _tf_apply "$log"
  _kubeconfig
  _istio_install "$log"
  # Taint Certificate + Gateway resources so pass 2 recreates them with Istio ready.
  if [[ "$DRY_RUN" != "true" ]]; then
    _step "Tainting Certificate + Gateway resources for pass 2"
    _cert_res=$(_tf state list 2>/dev/null | grep "terraform_data.langsmith_certificate" || echo "")
    _gw_res=$(_tf state list 2>/dev/null | grep "terraform_data.istio_gateway_tls" || echo "")
    [[ -n "$_cert_res" ]] && terraform -chdir="$INFRA_DIR" taint "$_cert_res" 2>/dev/null || true
    [[ -n "$_gw_res" ]] && terraform -chdir="$INFRA_DIR" taint "$_gw_res" 2>/dev/null || true
    _ok "Resources tainted for pass 2"
  fi
  _step "terraform apply (pass 2 — Certificate + Gateway provisioners)"
  [[ "$DRY_RUN" != "true" ]] && _tf apply -auto-approve >> "$log" 2>&1 && _ok "Pass 2 applied"

  _step "Phase 2: Running terraform destroy (with DNS-01 active)..."
  _helm_uninstall "$log"
  _tf_destroy "$log"
  _istio_uninstall "$log"

  # Post-destroy assertions — nothing should remain
  _step "Asserting no orphaned Kubernetes resources..."
  _assert_k8s_absent "ClusterIssuer letsencrypt-prod deleted" \
    "kubectl get clusterissuer letsencrypt-prod -o name 2>/dev/null"
  _assert_k8s_absent "Certificate langsmith-tls deleted from istio-system" \
    "kubectl get certificate langsmith-tls -n istio-system -o name 2>/dev/null"
  _assert_k8s_absent "TLS secret langsmith-tls deleted from istio-system" \
    "kubectl get secret langsmith-tls -n istio-system -o name 2>/dev/null"

  _step "Asserting no orphaned IAM resources..."
  local role_name="${_cluster_name}-cert-manager"
  _assert_k8s_absent "cert-manager IAM role deleted" \
    "aws iam get-role --role-name $role_name --query 'Role.RoleName' --output text 2>/dev/null"

  local policy_name="${_cluster_name}-cert-manager-route53"
  _assert_k8s_absent "cert-manager IAM policy deleted" \
    "aws iam list-policies --scope Local --query \"Policies[?PolicyName=='$policy_name'].PolicyName\" --output text 2>/dev/null"

  _print_results "$name" "$ts"
}

run_8() {
  local name="P8: Envoy Gateway + tls=none"
  local ts; ts=$(date +%Y%m%d-%H%M%S)
  local logdir="$LOG_DIR/p8-envoy-none-$ts"
  mkdir -p "$logdir"
  local log="$logdir/run.log"
  _reset_results

  _section "$name"

  if [[ -z "$_domain" ]]; then
    _warn "Skipping $name — langsmith_domain not set (needed for Gateway hosts field)"
    return 0
  fi

  _write_override "tls_certificate_source  = \"none\"
langsmith_domain        = \"${_domain}\"
enable_envoy_gateway    = true
enable_istio_gateway    = false
create_cert_manager_irsa = false"

  _helm_uninstall "$log"
  _tf_destroy "$log"
  _tf_apply "$log"
  _kubeconfig
  _helm_deploy "$log"

  # Wait for GatewayClass to be accepted and Gateway to be programmed.
  # The terraform_data provisioner creates these immediately after Helm install
  # but the Envoy Gateway controller needs ~30-60s to reconcile them.
  _step "Waiting for GatewayClass 'eg' to be Accepted (up to 3 min)..."
  if [[ "$DRY_RUN" != "true" ]]; then
    for i in $(seq 1 18); do
      local _gc_accepted
      _gc_accepted=$(kubectl get gatewayclass eg \
        -o jsonpath='{.status.conditions[?(@.type=="Accepted")].status}' 2>/dev/null || echo "")
      [[ "$_gc_accepted" == "True" ]] && break
      sleep 10
    done
  fi

  _step "Waiting for Gateway 'langsmith-gateway' to be Programmed (up to 3 min)..."
  if [[ "$DRY_RUN" != "true" ]]; then
    for i in $(seq 1 18); do
      local _gw_prog
      _gw_prog=$(kubectl get gateway langsmith-gateway -n langsmith \
        -o jsonpath='{.status.conditions[?(@.type=="Programmed")].status}' 2>/dev/null || echo "")
      [[ "$_gw_prog" == "True" ]] && break
      sleep 10
    done
  fi

  _step "Running assertions..."

  # Control plane
  _assert_k8s "envoy-gateway deployment ready" \
    "kubectl get deployment envoy-gateway -n envoy-gateway-system \
       -o jsonpath='{.status.readyReplicas}'" \
    "$(kubectl get deployment envoy-gateway -n envoy-gateway-system \
         -o jsonpath='{.spec.replicas}' 2>/dev/null || echo "1")"

  # GatewayClass
  _assert_k8s "GatewayClass 'eg' accepted" \
    "kubectl get gatewayclass eg \
       -o jsonpath='{.status.conditions[?(@.type==\"Accepted\")].status}'" \
    "True"

  # Gateway
  _assert_k8s "Gateway langsmith-gateway exists in langsmith ns" \
    "kubectl get gateway langsmith-gateway -n langsmith \
       -o jsonpath='{.metadata.name}'" \
    "langsmith-gateway"

  _assert_k8s "Gateway has HTTP listener on port 80" \
    "kubectl get gateway langsmith-gateway -n langsmith \
       -o jsonpath='{.spec.listeners[?(@.port==80)].name}'" \
    "http"

  # NLB provisioned by Envoy Gateway — wait up to 5 min for hostname
  _step "Waiting for Envoy Gateway NLB hostname (up to 5 min)..."
  local nlb_host=""
  if [[ "$DRY_RUN" != "true" ]]; then
    for i in $(seq 1 30); do
      nlb_host=$(kubectl get svc -n envoy-gateway-system \
        -l "gateway.envoyproxy.io/owning-gateway-name=langsmith-gateway" \
        -o jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo "")
      [[ -n "$nlb_host" ]] && break
      sleep 10
    done
  fi
  _assert "Envoy Gateway NLB hostname provisioned" \
    "$([[ -n "$nlb_host" ]] && echo true || echo false)" "$nlb_host"

  # HTTPRoute
  _assert_k8s_exists "HTTPRoute langsmith exists" \
    "kubectl get httproute -n langsmith -o name 2>/dev/null | grep langsmith | head -1"

  # Traffic — wait up to 3 min for NLB to become traffic-ready
  # (hostname appears in AWS before the LB finishes health-check probing)
  _step "Waiting for NLB to serve traffic on http://${nlb_host}/api/v1/health (up to 3 min)..."
  if [[ "$DRY_RUN" != "true" && -n "$nlb_host" ]]; then
    for i in $(seq 1 18); do
      local _hc
      _hc=$(curl -sk -o /dev/null -w "%{http_code}" --max-time 10 \
        "http://${nlb_host}/api/v1/health" 2>/dev/null || echo "000")
      [[ "$_hc" == "200" ]] && break
      sleep 10
    done
  fi
  _assert_http "GET http://${nlb_host}/api/v1/health → 200" \
    "http://${nlb_host}/api/v1/health"

  _assert_k8s_absent "No ClusterIssuer letsencrypt-prod" \
    "kubectl get clusterissuer letsencrypt-prod -o name 2>/dev/null"
  _assert_k8s_absent "No Istio istiod deployment" \
    "kubectl get deployment istiod -n istio-system -o name 2>/dev/null"

  _print_results "$name" "$ts"
}

# ── Main: run selected permutations ──────────────────────────────────────────

trap '_cleanup_override' EXIT

echo ""
printf '\033[1m════════════════════════════════════════════════════════\033[0m\n'
printf '\033[1m  LangSmith AWS — Permutation Test Suite\033[0m\n'
printf '\033[1m════════════════════════════════════════════════════════\033[0m\n'
echo ""
echo "  Cluster:  ${_cluster_name}"
echo "  Domain:   ${_domain:-<not set>}"
echo "  Email:    ${_le_email:-<not set>}"
echo "  Zone:     ${_hosted_zone:-<not set>}"
echo "  Logs:     ${LOG_DIR}"
[[ "$DRY_RUN" == "true" ]]    && echo "  Mode:     DRY RUN (no changes applied)"
[[ "$SKIP_DESTROY" == "true" ]] && echo "  Mode:     skip-destroy active"
echo ""

date >> "$SUMMARY_LOG"
echo "Cluster: $_cluster_name  Domain: ${_domain:-none}" >> "$SUMMARY_LOG"

_GRAND_PASS=0
_GRAND_FAIL=0

_run_permutation() {
  local n="$1"
  "run_${n}" || true
  _GRAND_PASS=$((_GRAND_PASS + _PASS))
  _GRAND_FAIL=$((_GRAND_FAIL + _FAIL))
}

if [[ "$RUN_ALL" == "true" ]]; then
  for n in 1 2 3 4 5 6 7 8; do _run_permutation "$n"; done
else
  for n in "${SELECTED[@]}"; do _run_permutation "$n"; done
fi

_cleanup_override

echo ""
printf '\033[1m════════════════════════════════════════════════════════\033[0m\n'
printf '\033[1m  Grand Total\033[0m\n'
echo "  Passed: ${_GRAND_PASS}"
echo "  Failed: ${_GRAND_FAIL}"
if [[ $_GRAND_FAIL -eq 0 ]]; then
  printf '  \033[32mAll permutations PASSED\033[0m\n'
else
  printf '  \033[31m%d permutation assertion(s) FAILED\033[0m\n' "$_GRAND_FAIL"
fi
printf '\033[1m════════════════════════════════════════════════════════\033[0m\n'
echo ""

[[ $_GRAND_FAIL -eq 0 ]]
