#!/usr/bin/env bash
# init-values.sh — Generates langsmith-values-overrides.yaml from Terraform outputs.
#
# Usage (from aws/):
#   make init-values  (or: ./helm/scripts/init-values.sh)
#
# Reads:
#   - aws/infra/terraform.tfvars    → name_prefix, environment, region, tls_certificate_source
#   - terraform output              → bucket_name, langsmith_irsa_role_arn, alb outputs
#
# Prompts for:
#   - Admin email (non-sensitive; written to values file)
#
# Writes:
#   - values/langsmith-values-overrides.yaml  (no secrets — ESO pulls those from SSM)
#
# Re-running is safe: Terraform outputs are refreshed; admin email is preserved
# if the file already exists.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HELM_DIR="$SCRIPT_DIR/.."
INFRA_DIR="$HELM_DIR/../infra"
VALUES_DIR="$HELM_DIR/values"
source "$INFRA_DIR/scripts/_common.sh"

# ── Parse terraform.tfvars ────────────────────────────────────────────────────
if [[ ! -f "$INFRA_DIR/terraform.tfvars" ]]; then
  echo "ERROR: terraform.tfvars not found at $INFRA_DIR/terraform.tfvars" >&2
  echo "Run: cp $INFRA_DIR/terraform.tfvars.example $INFRA_DIR/terraform.tfvars" >&2
  exit 1
fi

_name_prefix=$(_parse_tfvar "name_prefix") || _name_prefix=""
_environment=$(_parse_tfvar "environment") || _environment="production"
_region=$(_parse_tfvar "region") || _region="${AWS_REGION:-us-east-2}"
_tls_source=$(_parse_tfvar "tls_certificate_source") || _tls_source="none"

# Derive protocol for config.deployment.url
if [[ "$_tls_source" == "acm" || "$_tls_source" == "letsencrypt" ]]; then
  _protocol="https"
else
  _protocol="http"
fi

OUT_FILE="$VALUES_DIR/langsmith-values-overrides.yaml"

echo "Parsed terraform.tfvars:"
echo "  name_prefix           = ${_name_prefix:-(empty)}"
echo "  environment           = $_environment"
echo "  region                = $_region"
echo "  tls_certificate_source= $_tls_source (deployment URL protocol: $_protocol)"
echo "  output file  = $OUT_FILE"
echo ""

# ── Terraform outputs ─────────────────────────────────────────────────────────
echo "Reading Terraform outputs..."

BUCKET_NAME=$(terraform -chdir="$INFRA_DIR" output -raw bucket_name 2>/dev/null) || {
  echo "ERROR: Could not read bucket_name. Is 'terraform apply' complete?" >&2; exit 1
}
IRSA_ROLE_ARN=$(terraform -chdir="$INFRA_DIR" output -raw langsmith_irsa_role_arn 2>/dev/null) || {
  echo "ERROR: Could not read langsmith_irsa_role_arn. Is 'terraform apply' complete?" >&2; exit 1
}
ALB_ARN=$(terraform -chdir="$INFRA_DIR" output -raw alb_arn 2>/dev/null) || ALB_ARN=""
ALB_DNS_NAME=$(terraform -chdir="$INFRA_DIR" output -raw alb_dns_name 2>/dev/null) || ALB_DNS_NAME=""

echo "  bucket_name             = $BUCKET_NAME"
echo "  langsmith_irsa_role_arn = $IRSA_ROLE_ARN"
echo "  alb_arn                 = ${ALB_ARN:-(not provisioned)}"
echo "  alb_dns_name            = ${ALB_DNS_NAME:-(not provisioned)}"
echo ""

# ── Hostname ──────────────────────────────────────────────────────────────────
EXISTING_HOSTNAME=""
if [[ -f "$OUT_FILE" ]]; then
  EXISTING_HOSTNAME=$(grep -E '^\s*hostname:' "$OUT_FILE" 2>/dev/null \
    | sed 's/.*:[[:space:]]*"\(.*\)".*/\1/' | tr -d '[:space:]') || EXISTING_HOSTNAME=""
fi
if [[ -n "$EXISTING_HOSTNAME" ]]; then
  HOSTNAME="$EXISTING_HOSTNAME"
elif [[ -n "$ALB_DNS_NAME" ]]; then
  HOSTNAME="$ALB_DNS_NAME"
else
  HOSTNAME=""
fi

# ── Admin email ───────────────────────────────────────────────────────────────
EXISTING_EMAIL=""
if [[ -f "$OUT_FILE" ]]; then
  EXISTING_EMAIL=$(grep -E '^\s*initialOrgAdminEmail:' "$OUT_FILE" 2>/dev/null \
    | sed 's/.*:[[:space:]]*"\(.*\)".*/\1/' | tr -d '[:space:]') || EXISTING_EMAIL=""
fi

if [[ -n "$EXISTING_EMAIL" ]]; then
  ADMIN_EMAIL="$EXISTING_EMAIL"
  echo "Reusing existing admin email: $ADMIN_EMAIL"
else
  printf "Admin email [admin@example.com]: "
  read -r ADMIN_EMAIL
  ADMIN_EMAIL="${ADMIN_EMAIL:-admin@example.com}"
fi
echo ""

# ── Build optional blocks ─────────────────────────────────────────────────────
_alb_annotation=""
if [[ -n "$ALB_ARN" ]]; then
  _alb_annotation="
ingress:
  annotations:
    alb.ingress.kubernetes.io/load-balancer-arn: \"${ALB_ARN}\""
fi

# ── Write langsmith-values-{env}.yaml ────────────────────────────────────────
# Secrets (license key, api key salt, jwt secret, admin password) are NOT written
# here. ESO pulls them from SSM and creates the 'langsmith-config' K8s Secret.
cat > "$OUT_FILE" << YAML
# Auto-generated by init-values.sh — do not edit auto-filled fields manually.
# Re-run init-values.sh to refresh Terraform outputs.
# Secrets are managed by External Secrets Operator (ESO) from SSM — see:
#   aws/infra/modules/k8s-bootstrap/main.tf

config:
  # ALB hostname — required for OAuth and Deployments features.
  # Find it with: kubectl get ingress -n langsmith langsmith-ingress \
  #     -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
  # Or check: AWS Console → EC2 → Load Balancers → DNS name
  hostname: "${HOSTNAME}"
  initialOrgAdminEmail: "${ADMIN_EMAIL}"
  deployment:
    # URL used by the operator to build agent deployment endpoints.
    # Must match config.hostname with correct protocol — wrong value keeps
    # deployments stuck in DEPLOYING state.
    url: "${_protocol}://${HOSTNAME}"
  blobStorage:
    bucketName: "${BUCKET_NAME}"
    awsRegion: "${_region}"
    apiURL: "https://s3.${_region}.amazonaws.com"

commonEnv:
  - name: AWS_REGION
    value: "${_region}"
  - name: AWS_DEFAULT_REGION
    value: "${_region}"

# IRSA: annotate each component's service account individually.
# The chart does not support a global serviceAccount block.
platformBackend:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${IRSA_ROLE_ARN}"

backend:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${IRSA_ROLE_ARN}"

ingestQueue:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${IRSA_ROLE_ARN}"

queue:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${IRSA_ROLE_ARN}"

# Deployments feature components — annotations are harmless if the addon is not enabled.
hostBackend:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${IRSA_ROLE_ARN}"

listener:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${IRSA_ROLE_ARN}"

operator:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${IRSA_ROLE_ARN}"
# langsmith-ksa is used by operator-spawned agent deployment pods and must also
# carry the IRSA annotation. Apply it after Helm creates the service account:
#   kubectl annotate serviceaccount langsmith-ksa -n langsmith \
#     eks.amazonaws.com/role-arn=<irsa_role_arn> --overwrite
${_alb_annotation}
YAML

echo "Written: $OUT_FILE"
echo ""

# ── Sizing defaults ───────────────────────────────────────────────────────────
# Enable HA sizing by default. Skip if the user has already chosen a sizing file.
_ha_file="$VALUES_DIR/langsmith-values-ha.yaml"
_dev_file="$VALUES_DIR/langsmith-values-dev.yaml"
if [[ ! -f "$_ha_file" && ! -f "$_dev_file" ]]; then
  cp "$VALUES_DIR/langsmith-values-ha.yaml.example" "$_ha_file"
  echo "Enabled HA sizing: langsmith-values-ha.yaml"
  echo "  (swap for langsmith-values-dev.yaml.example for dev/test/POC deployments)"
  echo ""
fi

echo "Next step: ./helm/scripts/deploy.sh"
